#ifndef _CSU_H_
#define _CSU_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "ronaldo-map.dtsh"

/**
 * CSU Base Address
 */
#define CSU_BASEADDR      CSU

/**
 * Register: CSU_CSU_STATUS
 */
#define CSU_CSU_STATUS    ( ( CSU_BASEADDR ) + 0X00000000 )

#define CSU_CSU_STATUS_UNUSED_SHIFT   2
#define CSU_CSU_STATUS_UNUSED_WIDTH   30
#define CSU_CSU_STATUS_UNUSED_MASK    0XFFFFFFFC

#define CSU_CSU_STATUS_BOOT_ENC_SHIFT   1
#define CSU_CSU_STATUS_BOOT_ENC_WIDTH   1
#define CSU_CSU_STATUS_BOOT_ENC_MASK    0X00000002

#define CSU_CSU_STATUS_BOOT_AUTH_SHIFT   0
#define CSU_CSU_STATUS_BOOT_AUTH_WIDTH   1
#define CSU_CSU_STATUS_BOOT_AUTH_MASK    0X00000001

/**
 * Register: CSU_CSU_CTRL
 */
#define CSU_CSU_CTRL    ( ( CSU_BASEADDR ) + 0X00000004 )

#define CSU_CSU_CTRL_SLVERR_ENABLE_SHIFT   4
#define CSU_CSU_CTRL_SLVERR_ENABLE_WIDTH   1
#define CSU_CSU_CTRL_SLVERR_ENABLE_MASK    0X00000010

#define CSU_CSU_CTRL_CSU_CLK_SEL_SHIFT   0
#define CSU_CSU_CTRL_CSU_CLK_SEL_WIDTH   1
#define CSU_CSU_CTRL_CSU_CLK_SEL_MASK    0X00000001

/**
 * Register: CSU_CSU_SSS_CFG
 */
#define CSU_CSU_SSS_CFG    ( ( CSU_BASEADDR ) + 0X00000008 )

#define CSU_CSU_SSS_CFG_PSTP_SSS_SHIFT   16
#define CSU_CSU_SSS_CFG_PSTP_SSS_WIDTH   4
#define CSU_CSU_SSS_CFG_PSTP_SSS_MASK    0X000F0000

#define CSU_CSU_SSS_CFG_SHA_SSS_SHIFT   12
#define CSU_CSU_SSS_CFG_SHA_SSS_WIDTH   4
#define CSU_CSU_SSS_CFG_SHA_SSS_MASK    0X0000F000

#define CSU_CSU_SSS_CFG_AES_SSS_SHIFT   8
#define CSU_CSU_SSS_CFG_AES_SSS_WIDTH   4
#define CSU_CSU_SSS_CFG_AES_SSS_MASK    0X00000F00

#define CSU_CSU_SSS_CFG_DMA_SSS_SHIFT   4
#define CSU_CSU_SSS_CFG_DMA_SSS_WIDTH   4
#define CSU_CSU_SSS_CFG_DMA_SSS_MASK    0X000000F0

#define CSU_CSU_SSS_CFG_PCAP_SSS_SHIFT   0
#define CSU_CSU_SSS_CFG_PCAP_SSS_WIDTH   4
#define CSU_CSU_SSS_CFG_PCAP_SSS_MASK    0X0000000F

/**
 * Register: CSU_CSU_DMA_RESET
 */
#define CSU_CSU_DMA_RESET    ( ( CSU_BASEADDR ) + 0X0000000C )

#define CSU_CSU_DMA_RESET_RESET_SHIFT   0
#define CSU_CSU_DMA_RESET_RESET_WIDTH   1
#define CSU_CSU_DMA_RESET_RESET_MASK    0X00000001

/**
 * Register: CSU_CSU_MULTI_BOOT
 */
#define CSU_CSU_MULTI_BOOT    ( ( CSU_BASEADDR ) + 0X00000010 )

#define CSU_CSU_MULTI_BOOT_MULTI_BOOT_ADDR_SHIFT   0
#define CSU_CSU_MULTI_BOOT_MULTI_BOOT_ADDR_WIDTH   32
#define CSU_CSU_MULTI_BOOT_MULTI_BOOT_ADDR_MASK    0XFFFFFFFF

/**
 * Register: CSU_CSU_TAMPER_TRIG
 */
#define CSU_CSU_TAMPER_TRIG    ( ( CSU_BASEADDR ) + 0X00000014 )

#define CSU_CSU_TAMPER_TRIG_TAMPER_SHIFT   0
#define CSU_CSU_TAMPER_TRIG_TAMPER_WIDTH   1
#define CSU_CSU_TAMPER_TRIG_TAMPER_MASK    0X00000001

/**
 * Register: CSU_CSU_FT_STATUS_0
 */
#define CSU_CSU_FT_STATUS_0    ( ( CSU_BASEADDR ) + 0X00000018 )

#define CSU_CSU_FT_STATUS_0_RAM_ECC_SHIFT   15
#define CSU_CSU_FT_STATUS_0_RAM_ECC_WIDTH   1
#define CSU_CSU_FT_STATUS_0_RAM_ECC_MASK    0X00008000

#define CSU_CSU_FT_STATUS_0_VOTE_ERROR_SHIFT   14
#define CSU_CSU_FT_STATUS_0_VOTE_ERROR_WIDTH   1
#define CSU_CSU_FT_STATUS_0_VOTE_ERROR_MASK    0X00004000

#define CSU_CSU_FT_STATUS_0_COMP_ERR_23_SHIFT   13
#define CSU_CSU_FT_STATUS_0_COMP_ERR_23_WIDTH   1
#define CSU_CSU_FT_STATUS_0_COMP_ERR_23_MASK    0X00002000

#define CSU_CSU_FT_STATUS_0_COMP_ERR_13_SHIFT   12
#define CSU_CSU_FT_STATUS_0_COMP_ERR_13_WIDTH   1
#define CSU_CSU_FT_STATUS_0_COMP_ERR_13_MASK    0X00001000

#define CSU_CSU_FT_STATUS_0_COMP_ERR_12_SHIFT   11
#define CSU_CSU_FT_STATUS_0_COMP_ERR_12_WIDTH   1
#define CSU_CSU_FT_STATUS_0_COMP_ERR_12_MASK    0X00000800

#define CSU_CSU_FT_STATUS_0_MISMATCH_23_A_SHIFT   10
#define CSU_CSU_FT_STATUS_0_MISMATCH_23_A_WIDTH   1
#define CSU_CSU_FT_STATUS_0_MISMATCH_23_A_MASK    0X00000400

#define CSU_CSU_FT_STATUS_0_MISMATCH_13_A_SHIFT   9
#define CSU_CSU_FT_STATUS_0_MISMATCH_13_A_WIDTH   1
#define CSU_CSU_FT_STATUS_0_MISMATCH_13_A_MASK    0X00000200

#define CSU_CSU_FT_STATUS_0_MISMATCH_12_A_SHIFT   8
#define CSU_CSU_FT_STATUS_0_MISMATCH_12_A_WIDTH   1
#define CSU_CSU_FT_STATUS_0_MISMATCH_12_A_MASK    0X00000100

#define CSU_CSU_FT_STATUS_0_SLEEP_RESET_SHIFT   3
#define CSU_CSU_FT_STATUS_0_SLEEP_RESET_WIDTH   1
#define CSU_CSU_FT_STATUS_0_SLEEP_RESET_MASK    0X00000008

#define CSU_CSU_FT_STATUS_0_MISMATCH_23_B_SHIFT   2
#define CSU_CSU_FT_STATUS_0_MISMATCH_23_B_WIDTH   1
#define CSU_CSU_FT_STATUS_0_MISMATCH_23_B_MASK    0X00000004

#define CSU_CSU_FT_STATUS_0_MISMATCH_13_B_SHIFT   1
#define CSU_CSU_FT_STATUS_0_MISMATCH_13_B_WIDTH   1
#define CSU_CSU_FT_STATUS_0_MISMATCH_13_B_MASK    0X00000002

#define CSU_CSU_FT_STATUS_0_MISMATCH_12_B_SHIFT   0
#define CSU_CSU_FT_STATUS_0_MISMATCH_12_B_WIDTH   1
#define CSU_CSU_FT_STATUS_0_MISMATCH_12_B_MASK    0X00000001

/**
 * Register: CSU_CSU_FT_STATUS_1
 */
#define CSU_CSU_FT_STATUS_1    ( ( CSU_BASEADDR ) + 0X0000001C )

#define CSU_CSU_FT_STATUS_1_RAM_ECC_SHIFT   15
#define CSU_CSU_FT_STATUS_1_RAM_ECC_WIDTH   1
#define CSU_CSU_FT_STATUS_1_RAM_ECC_MASK    0X00008000

#define CSU_CSU_FT_STATUS_1_VOTE_ERROR_SHIFT   14
#define CSU_CSU_FT_STATUS_1_VOTE_ERROR_WIDTH   1
#define CSU_CSU_FT_STATUS_1_VOTE_ERROR_MASK    0X00004000

#define CSU_CSU_FT_STATUS_1_COMP_ERR_23_SHIFT   13
#define CSU_CSU_FT_STATUS_1_COMP_ERR_23_WIDTH   1
#define CSU_CSU_FT_STATUS_1_COMP_ERR_23_MASK    0X00002000

#define CSU_CSU_FT_STATUS_1_COMP_ERR_13_SHIFT   12
#define CSU_CSU_FT_STATUS_1_COMP_ERR_13_WIDTH   1
#define CSU_CSU_FT_STATUS_1_COMP_ERR_13_MASK    0X00001000

#define CSU_CSU_FT_STATUS_1_COMP_ERR_12_SHIFT   11
#define CSU_CSU_FT_STATUS_1_COMP_ERR_12_WIDTH   1
#define CSU_CSU_FT_STATUS_1_COMP_ERR_12_MASK    0X00000800

#define CSU_CSU_FT_STATUS_1_MISMATCH_23_A_SHIFT   10
#define CSU_CSU_FT_STATUS_1_MISMATCH_23_A_WIDTH   1
#define CSU_CSU_FT_STATUS_1_MISMATCH_23_A_MASK    0X00000400

#define CSU_CSU_FT_STATUS_1_MISMATCH_13_A_SHIFT   9
#define CSU_CSU_FT_STATUS_1_MISMATCH_13_A_WIDTH   1
#define CSU_CSU_FT_STATUS_1_MISMATCH_13_A_MASK    0X00000200

#define CSU_CSU_FT_STATUS_1_MISMATCH_12_A_SHIFT   8
#define CSU_CSU_FT_STATUS_1_MISMATCH_12_A_WIDTH   1
#define CSU_CSU_FT_STATUS_1_MISMATCH_12_A_MASK    0X00000100

#define CSU_CSU_FT_STATUS_1_SLEEP_RESET_SHIFT   3
#define CSU_CSU_FT_STATUS_1_SLEEP_RESET_WIDTH   1
#define CSU_CSU_FT_STATUS_1_SLEEP_RESET_MASK    0X00000008

#define CSU_CSU_FT_STATUS_1_MISMATCH_23_B_SHIFT   2
#define CSU_CSU_FT_STATUS_1_MISMATCH_23_B_WIDTH   1
#define CSU_CSU_FT_STATUS_1_MISMATCH_23_B_MASK    0X00000004

#define CSU_CSU_FT_STATUS_1_MISMATCH_13_B_SHIFT   1
#define CSU_CSU_FT_STATUS_1_MISMATCH_13_B_WIDTH   1
#define CSU_CSU_FT_STATUS_1_MISMATCH_13_B_MASK    0X00000002

#define CSU_CSU_FT_STATUS_1_MISMATCH_12_B_SHIFT   0
#define CSU_CSU_FT_STATUS_1_MISMATCH_12_B_WIDTH   1
#define CSU_CSU_FT_STATUS_1_MISMATCH_12_B_MASK    0X00000001

/**
 * Register: CSU_CSU_ISR
 */
#define CSU_CSU_ISR    ( ( CSU_BASEADDR ) + 0X00000020 )

#define CSU_CSU_ISR_UNUSED_SHIFT   12
#define CSU_CSU_ISR_UNUSED_WIDTH   20
#define CSU_CSU_ISR_UNUSED_MASK    0XFFFFF000

#define CSU_CSU_ISR_APB_SLVERR_SHIFT   11
#define CSU_CSU_ISR_APB_SLVERR_WIDTH   1
#define CSU_CSU_ISR_APB_SLVERR_MASK    0X00000800

#define CSU_CSU_ISR_TMR_FATAL_SHIFT   10
#define CSU_CSU_ISR_TMR_FATAL_WIDTH   1
#define CSU_CSU_ISR_TMR_FATAL_MASK    0X00000400

#define CSU_CSU_ISR_PL_SEU_ERROR_SHIFT   9
#define CSU_CSU_ISR_PL_SEU_ERROR_WIDTH   1
#define CSU_CSU_ISR_PL_SEU_ERROR_MASK    0X00000200

#define CSU_CSU_ISR_AES_ERROR_SHIFT   8
#define CSU_CSU_ISR_AES_ERROR_WIDTH   1
#define CSU_CSU_ISR_AES_ERROR_MASK    0X00000100

#define CSU_CSU_ISR_PCAP_WR_OVERFLOW_SHIFT   7
#define CSU_CSU_ISR_PCAP_WR_OVERFLOW_WIDTH   1
#define CSU_CSU_ISR_PCAP_WR_OVERFLOW_MASK    0X00000080

#define CSU_CSU_ISR_PCAP_RD_OVERFLOW_SHIFT   6
#define CSU_CSU_ISR_PCAP_RD_OVERFLOW_WIDTH   1
#define CSU_CSU_ISR_PCAP_RD_OVERFLOW_MASK    0X00000040

#define CSU_CSU_ISR_PL_POR_B_SHIFT   5
#define CSU_CSU_ISR_PL_POR_B_WIDTH   1
#define CSU_CSU_ISR_PL_POR_B_MASK    0X00000020

#define CSU_CSU_ISR_PL_INIT_SHIFT   4
#define CSU_CSU_ISR_PL_INIT_WIDTH   1
#define CSU_CSU_ISR_PL_INIT_MASK    0X00000010

#define CSU_CSU_ISR_PL_DONE_SHIFT   3
#define CSU_CSU_ISR_PL_DONE_WIDTH   1
#define CSU_CSU_ISR_PL_DONE_MASK    0X00000008

#define CSU_CSU_ISR_SHA_DONE_SHIFT   2
#define CSU_CSU_ISR_SHA_DONE_WIDTH   1
#define CSU_CSU_ISR_SHA_DONE_MASK    0X00000004

#define CSU_CSU_ISR_RSA_DONE_SHIFT   1
#define CSU_CSU_ISR_RSA_DONE_WIDTH   1
#define CSU_CSU_ISR_RSA_DONE_MASK    0X00000002

#define CSU_CSU_ISR_AES_DONE_SHIFT   0
#define CSU_CSU_ISR_AES_DONE_WIDTH   1
#define CSU_CSU_ISR_AES_DONE_MASK    0X00000001

/**
 * Register: CSU_CSU_IMR
 */
#define CSU_CSU_IMR    ( ( CSU_BASEADDR ) + 0X00000024 )

#define CSU_CSU_IMR_UNUSED_SHIFT   12
#define CSU_CSU_IMR_UNUSED_WIDTH   20
#define CSU_CSU_IMR_UNUSED_MASK    0XFFFFF000

#define CSU_CSU_IMR_APB_SLVERR_SHIFT   11
#define CSU_CSU_IMR_APB_SLVERR_WIDTH   1
#define CSU_CSU_IMR_APB_SLVERR_MASK    0X00000800

#define CSU_CSU_IMR_TMR_FATAL_SHIFT   10
#define CSU_CSU_IMR_TMR_FATAL_WIDTH   1
#define CSU_CSU_IMR_TMR_FATAL_MASK    0X00000400

#define CSU_CSU_IMR_PL_SEU_ERROR_SHIFT   9
#define CSU_CSU_IMR_PL_SEU_ERROR_WIDTH   1
#define CSU_CSU_IMR_PL_SEU_ERROR_MASK    0X00000200

#define CSU_CSU_IMR_AES_ERROR_SHIFT   8
#define CSU_CSU_IMR_AES_ERROR_WIDTH   1
#define CSU_CSU_IMR_AES_ERROR_MASK    0X00000100

#define CSU_CSU_IMR_PCAP_WR_OVERFLOW_SHIFT   7
#define CSU_CSU_IMR_PCAP_WR_OVERFLOW_WIDTH   1
#define CSU_CSU_IMR_PCAP_WR_OVERFLOW_MASK    0X00000080

#define CSU_CSU_IMR_PCAP_RD_OVERFLOW_SHIFT   6
#define CSU_CSU_IMR_PCAP_RD_OVERFLOW_WIDTH   1
#define CSU_CSU_IMR_PCAP_RD_OVERFLOW_MASK    0X00000040

#define CSU_CSU_IMR_PL_POR_B_SHIFT   5
#define CSU_CSU_IMR_PL_POR_B_WIDTH   1
#define CSU_CSU_IMR_PL_POR_B_MASK    0X00000020

#define CSU_CSU_IMR_PL_INIT_SHIFT   4
#define CSU_CSU_IMR_PL_INIT_WIDTH   1
#define CSU_CSU_IMR_PL_INIT_MASK    0X00000010

#define CSU_CSU_IMR_PL_DONE_SHIFT   3
#define CSU_CSU_IMR_PL_DONE_WIDTH   1
#define CSU_CSU_IMR_PL_DONE_MASK    0X00000008

#define CSU_CSU_IMR_SHA_DONE_SHIFT   2
#define CSU_CSU_IMR_SHA_DONE_WIDTH   1
#define CSU_CSU_IMR_SHA_DONE_MASK    0X00000004

#define CSU_CSU_IMR_RSA_DONE_SHIFT   1
#define CSU_CSU_IMR_RSA_DONE_WIDTH   1
#define CSU_CSU_IMR_RSA_DONE_MASK    0X00000002

#define CSU_CSU_IMR_AES_DONE_SHIFT   0
#define CSU_CSU_IMR_AES_DONE_WIDTH   1
#define CSU_CSU_IMR_AES_DONE_MASK    0X00000001

/**
 * Register: CSU_CSU_IER
 */
#define CSU_CSU_IER    ( ( CSU_BASEADDR ) + 0X00000028 )

#define CSU_CSU_IER_UNUSED_SHIFT   12
#define CSU_CSU_IER_UNUSED_WIDTH   20
#define CSU_CSU_IER_UNUSED_MASK    0XFFFFF000

#define CSU_CSU_IER_APB_SLVERR_SHIFT   11
#define CSU_CSU_IER_APB_SLVERR_WIDTH   1
#define CSU_CSU_IER_APB_SLVERR_MASK    0X00000800

#define CSU_CSU_IER_TMR_FATAL_SHIFT   10
#define CSU_CSU_IER_TMR_FATAL_WIDTH   1
#define CSU_CSU_IER_TMR_FATAL_MASK    0X00000400

#define CSU_CSU_IER_PL_SEU_ERROR_SHIFT   9
#define CSU_CSU_IER_PL_SEU_ERROR_WIDTH   1
#define CSU_CSU_IER_PL_SEU_ERROR_MASK    0X00000200

#define CSU_CSU_IER_AES_ERROR_SHIFT   8
#define CSU_CSU_IER_AES_ERROR_WIDTH   1
#define CSU_CSU_IER_AES_ERROR_MASK    0X00000100

#define CSU_CSU_IER_PCAP_WR_OVERFLOW_SHIFT   7
#define CSU_CSU_IER_PCAP_WR_OVERFLOW_WIDTH   1
#define CSU_CSU_IER_PCAP_WR_OVERFLOW_MASK    0X00000080

#define CSU_CSU_IER_PCAP_RD_OVERFLOW_SHIFT   6
#define CSU_CSU_IER_PCAP_RD_OVERFLOW_WIDTH   1
#define CSU_CSU_IER_PCAP_RD_OVERFLOW_MASK    0X00000040

#define CSU_CSU_IER_PL_POR_B_SHIFT   5
#define CSU_CSU_IER_PL_POR_B_WIDTH   1
#define CSU_CSU_IER_PL_POR_B_MASK    0X00000020

#define CSU_CSU_IER_PL_INIT_SHIFT   4
#define CSU_CSU_IER_PL_INIT_WIDTH   1
#define CSU_CSU_IER_PL_INIT_MASK    0X00000010

#define CSU_CSU_IER_PL_DONE_SHIFT   3
#define CSU_CSU_IER_PL_DONE_WIDTH   1
#define CSU_CSU_IER_PL_DONE_MASK    0X00000008

#define CSU_CSU_IER_SHA_DONE_SHIFT   2
#define CSU_CSU_IER_SHA_DONE_WIDTH   1
#define CSU_CSU_IER_SHA_DONE_MASK    0X00000004

#define CSU_CSU_IER_RSA_DONE_SHIFT   1
#define CSU_CSU_IER_RSA_DONE_WIDTH   1
#define CSU_CSU_IER_RSA_DONE_MASK    0X00000002

#define CSU_CSU_IER_AES_DONE_SHIFT   0
#define CSU_CSU_IER_AES_DONE_WIDTH   1
#define CSU_CSU_IER_AES_DONE_MASK    0X00000001

/**
 * Register: CSU_CSU_IDR
 */
#define CSU_CSU_IDR    ( ( CSU_BASEADDR ) + 0X0000002C )

#define CSU_CSU_IDR_UNUSED_SHIFT   12
#define CSU_CSU_IDR_UNUSED_WIDTH   20
#define CSU_CSU_IDR_UNUSED_MASK    0XFFFFF000

#define CSU_CSU_IDR_APB_SLVERR_SHIFT   11
#define CSU_CSU_IDR_APB_SLVERR_WIDTH   1
#define CSU_CSU_IDR_APB_SLVERR_MASK    0X00000800

#define CSU_CSU_IDR_TMR_FATAL_SHIFT   10
#define CSU_CSU_IDR_TMR_FATAL_WIDTH   1
#define CSU_CSU_IDR_TMR_FATAL_MASK    0X00000400

#define CSU_CSU_IDR_PL_SEU_ERROR_SHIFT   9
#define CSU_CSU_IDR_PL_SEU_ERROR_WIDTH   1
#define CSU_CSU_IDR_PL_SEU_ERROR_MASK    0X00000200

#define CSU_CSU_IDR_AES_ERROR_SHIFT   8
#define CSU_CSU_IDR_AES_ERROR_WIDTH   1
#define CSU_CSU_IDR_AES_ERROR_MASK    0X00000100

#define CSU_CSU_IDR_PCAP_WR_OVERFLOW_SHIFT   7
#define CSU_CSU_IDR_PCAP_WR_OVERFLOW_WIDTH   1
#define CSU_CSU_IDR_PCAP_WR_OVERFLOW_MASK    0X00000080

#define CSU_CSU_IDR_PCAP_RD_OVERFLOW_SHIFT   6
#define CSU_CSU_IDR_PCAP_RD_OVERFLOW_WIDTH   1
#define CSU_CSU_IDR_PCAP_RD_OVERFLOW_MASK    0X00000040

#define CSU_CSU_IDR_PL_POR_B_SHIFT   5
#define CSU_CSU_IDR_PL_POR_B_WIDTH   1
#define CSU_CSU_IDR_PL_POR_B_MASK    0X00000020

#define CSU_CSU_IDR_PL_INIT_SHIFT   4
#define CSU_CSU_IDR_PL_INIT_WIDTH   1
#define CSU_CSU_IDR_PL_INIT_MASK    0X00000010

#define CSU_CSU_IDR_PL_DONE_SHIFT   3
#define CSU_CSU_IDR_PL_DONE_WIDTH   1
#define CSU_CSU_IDR_PL_DONE_MASK    0X00000008

#define CSU_CSU_IDR_SHA_DONE_SHIFT   2
#define CSU_CSU_IDR_SHA_DONE_WIDTH   1
#define CSU_CSU_IDR_SHA_DONE_MASK    0X00000004

#define CSU_CSU_IDR_RSA_DONE_SHIFT   1
#define CSU_CSU_IDR_RSA_DONE_WIDTH   1
#define CSU_CSU_IDR_RSA_DONE_MASK    0X00000002

#define CSU_CSU_IDR_AES_DONE_SHIFT   0
#define CSU_CSU_IDR_AES_DONE_WIDTH   1
#define CSU_CSU_IDR_AES_DONE_MASK    0X00000001

/**
 * Register: CSU_JTAG_CHAIN_CFG
 */
#define CSU_JTAG_CHAIN_CFG    ( ( CSU_BASEADDR ) + 0X00000030 )

#define CSU_JTAG_CHAIN_CFG_LINK_ARM_DAP_SHIFT   1
#define CSU_JTAG_CHAIN_CFG_LINK_ARM_DAP_WIDTH   1
#define CSU_JTAG_CHAIN_CFG_LINK_ARM_DAP_MASK    0X00000002

#define CSU_JTAG_CHAIN_CFG_LINK_PL_TAP_SHIFT   0
#define CSU_JTAG_CHAIN_CFG_LINK_PL_TAP_WIDTH   1
#define CSU_JTAG_CHAIN_CFG_LINK_PL_TAP_MASK    0X00000001

/**
 * Register: CSU_JTAG_CHAIN_STATUS
 */
#define CSU_JTAG_CHAIN_STATUS    ( ( CSU_BASEADDR ) + 0X00000034 )

#define CSU_JTAG_CHAIN_STATUS_ARM_DAP_SHIFT   1
#define CSU_JTAG_CHAIN_STATUS_ARM_DAP_WIDTH   1
#define CSU_JTAG_CHAIN_STATUS_ARM_DAP_MASK    0X00000002

#define CSU_JTAG_CHAIN_STATUS_PL_TAP_SHIFT   0
#define CSU_JTAG_CHAIN_STATUS_PL_TAP_WIDTH   1
#define CSU_JTAG_CHAIN_STATUS_PL_TAP_MASK    0X00000001

/**
 * Register: CSU_JTAG_SEC
 */
#define CSU_JTAG_SEC    ( ( CSU_BASEADDR ) + 0X00000038 )

#define CSU_JTAG_SEC_SEC_GATE_SHIFT   0
#define CSU_JTAG_SEC_SEC_GATE_WIDTH   3
#define CSU_JTAG_SEC_SEC_GATE_MASK    0X00000007

/**
 * Register: CSU_JTAG_DAP_CFG
 */
#define CSU_JTAG_DAP_CFG    ( ( CSU_BASEADDR ) + 0X0000003C )

#define CSU_JTAG_DAP_CFG_RPU_NIDEN_SHIFT   5
#define CSU_JTAG_DAP_CFG_RPU_NIDEN_WIDTH   1
#define CSU_JTAG_DAP_CFG_RPU_NIDEN_MASK    0X00000020

#define CSU_JTAG_DAP_CFG_RPU_DBGEN_SHIFT   4
#define CSU_JTAG_DAP_CFG_RPU_DBGEN_WIDTH   1
#define CSU_JTAG_DAP_CFG_RPU_DBGEN_MASK    0X00000010

#define CSU_JTAG_DAP_CFG_APU_SPNIDEN_SHIFT   3
#define CSU_JTAG_DAP_CFG_APU_SPNIDEN_WIDTH   1
#define CSU_JTAG_DAP_CFG_APU_SPNIDEN_MASK    0X00000008

#define CSU_JTAG_DAP_CFG_APU_SPIDEN_SHIFT   2
#define CSU_JTAG_DAP_CFG_APU_SPIDEN_WIDTH   1
#define CSU_JTAG_DAP_CFG_APU_SPIDEN_MASK    0X00000004

#define CSU_JTAG_DAP_CFG_APU_NIDEN_SHIFT   1
#define CSU_JTAG_DAP_CFG_APU_NIDEN_WIDTH   1
#define CSU_JTAG_DAP_CFG_APU_NIDEN_MASK    0X00000002

#define CSU_JTAG_DAP_CFG_APU_DBGEN_SHIFT   0
#define CSU_JTAG_DAP_CFG_APU_DBGEN_WIDTH   1
#define CSU_JTAG_DAP_CFG_APU_DBGEN_MASK    0X00000001

/**
 * Register: CSU_IDCODE
 */
#define CSU_IDCODE    ( ( CSU_BASEADDR ) + 0X00000040 )

#define CSU_IDCODE_REVISION_SHIFT   28
#define CSU_IDCODE_REVISION_WIDTH   4
#define CSU_IDCODE_REVISION_MASK    0XF0000000

#define CSU_IDCODE_FAMILY_SHIFT   21
#define CSU_IDCODE_FAMILY_WIDTH   7
#define CSU_IDCODE_FAMILY_MASK    0X0FE00000

#define CSU_IDCODE_SUBFAMILY_SHIFT   17
#define CSU_IDCODE_SUBFAMILY_WIDTH   4
#define CSU_IDCODE_SUBFAMILY_MASK    0X001E0000

#define CSU_IDCODE_DEVICE_SHIFT   12
#define CSU_IDCODE_DEVICE_WIDTH   5
#define CSU_IDCODE_DEVICE_MASK    0X0001F000

#define CSU_IDCODE_MANUFACTURER_SHIFT   1
#define CSU_IDCODE_MANUFACTURER_WIDTH   11
#define CSU_IDCODE_MANUFACTURER_MASK    0X00000FFE

/**
 * Register: CSU_VERSION
 */
#define CSU_VERSION    ( ( CSU_BASEADDR ) + 0X00000044 )

#define CSU_VERSION_PLATFORM_VERSION_SHIFT   16
#define CSU_VERSION_PLATFORM_VERSION_WIDTH   4
#define CSU_VERSION_PLATFORM_VERSION_MASK    0X000F0000

#define CSU_VERSION_PLATFORM_SHIFT   12
#define CSU_VERSION_PLATFORM_WIDTH   4
#define CSU_VERSION_PLATFORM_MASK    0X0000F000

#define CSU_VERSION_RTL_VERSION_SHIFT   4
#define CSU_VERSION_RTL_VERSION_WIDTH   8
#define CSU_VERSION_RTL_VERSION_MASK    0X00000FF0

#define CSU_VERSION_PS_VERSION_SHIFT   0
#define CSU_VERSION_PS_VERSION_WIDTH   4
#define CSU_VERSION_PS_VERSION_MASK    0X0000000F

/**
 * Register: CSU_CSU_ROM_DIGEST_0
 */
#define CSU_CSU_ROM_DIGEST_0    ( ( CSU_BASEADDR ) + 0X00000050 )

#define CSU_CSU_ROM_DIGEST_0_DIGEST_SHIFT   0
#define CSU_CSU_ROM_DIGEST_0_DIGEST_WIDTH   32
#define CSU_CSU_ROM_DIGEST_0_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_CSU_ROM_DIGEST_1
 */
#define CSU_CSU_ROM_DIGEST_1    ( ( CSU_BASEADDR ) + 0X00000054 )

#define CSU_CSU_ROM_DIGEST_1_DIGEST_SHIFT   0
#define CSU_CSU_ROM_DIGEST_1_DIGEST_WIDTH   32
#define CSU_CSU_ROM_DIGEST_1_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_CSU_ROM_DIGEST_2
 */
#define CSU_CSU_ROM_DIGEST_2    ( ( CSU_BASEADDR ) + 0X00000058 )

#define CSU_CSU_ROM_DIGEST_2_DIGEST_SHIFT   0
#define CSU_CSU_ROM_DIGEST_2_DIGEST_WIDTH   32
#define CSU_CSU_ROM_DIGEST_2_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_CSU_ROM_DIGEST_3
 */
#define CSU_CSU_ROM_DIGEST_3    ( ( CSU_BASEADDR ) + 0X0000005C )

#define CSU_CSU_ROM_DIGEST_3_DIGEST_SHIFT   0
#define CSU_CSU_ROM_DIGEST_3_DIGEST_WIDTH   32
#define CSU_CSU_ROM_DIGEST_3_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_CSU_ROM_DIGEST_4
 */
#define CSU_CSU_ROM_DIGEST_4    ( ( CSU_BASEADDR ) + 0X00000060 )

#define CSU_CSU_ROM_DIGEST_4_DIGEST_SHIFT   0
#define CSU_CSU_ROM_DIGEST_4_DIGEST_WIDTH   32
#define CSU_CSU_ROM_DIGEST_4_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_CSU_ROM_DIGEST_5
 */
#define CSU_CSU_ROM_DIGEST_5    ( ( CSU_BASEADDR ) + 0X00000064 )

#define CSU_CSU_ROM_DIGEST_5_DIGEST_SHIFT   0
#define CSU_CSU_ROM_DIGEST_5_DIGEST_WIDTH   32
#define CSU_CSU_ROM_DIGEST_5_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_CSU_ROM_DIGEST_6
 */
#define CSU_CSU_ROM_DIGEST_6    ( ( CSU_BASEADDR ) + 0X00000068 )

#define CSU_CSU_ROM_DIGEST_6_DIGEST_SHIFT   0
#define CSU_CSU_ROM_DIGEST_6_DIGEST_WIDTH   32
#define CSU_CSU_ROM_DIGEST_6_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_CSU_ROM_DIGEST_7
 */
#define CSU_CSU_ROM_DIGEST_7    ( ( CSU_BASEADDR ) + 0X0000006C )

#define CSU_CSU_ROM_DIGEST_7_DIGEST_SHIFT   0
#define CSU_CSU_ROM_DIGEST_7_DIGEST_WIDTH   32
#define CSU_CSU_ROM_DIGEST_7_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_CSU_ROM_DIGEST_8
 */
#define CSU_CSU_ROM_DIGEST_8    ( ( CSU_BASEADDR ) + 0X00000070 )

#define CSU_CSU_ROM_DIGEST_8_DIGEST_SHIFT   0
#define CSU_CSU_ROM_DIGEST_8_DIGEST_WIDTH   32
#define CSU_CSU_ROM_DIGEST_8_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_CSU_ROM_DIGEST_9
 */
#define CSU_CSU_ROM_DIGEST_9    ( ( CSU_BASEADDR ) + 0X00000074 )

#define CSU_CSU_ROM_DIGEST_9_DIGEST_SHIFT   0
#define CSU_CSU_ROM_DIGEST_9_DIGEST_WIDTH   32
#define CSU_CSU_ROM_DIGEST_9_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_CSU_ROM_DIGEST_10
 */
#define CSU_CSU_ROM_DIGEST_10    ( ( CSU_BASEADDR ) + 0X00000078 )

#define CSU_CSU_ROM_DIGEST_10_DIGEST_SHIFT   0
#define CSU_CSU_ROM_DIGEST_10_DIGEST_WIDTH   32
#define CSU_CSU_ROM_DIGEST_10_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_CSU_ROM_DIGEST_11
 */
#define CSU_CSU_ROM_DIGEST_11    ( ( CSU_BASEADDR ) + 0X0000007C )

#define CSU_CSU_ROM_DIGEST_11_DIGEST_SHIFT   0
#define CSU_CSU_ROM_DIGEST_11_DIGEST_WIDTH   32
#define CSU_CSU_ROM_DIGEST_11_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_AES_STATUS
 */
#define CSU_AES_STATUS    ( ( CSU_BASEADDR ) + 0X00001000 )

#define CSU_AES_STATUS_OKR_ZEROED_SHIFT   11
#define CSU_AES_STATUS_OKR_ZEROED_WIDTH   1
#define CSU_AES_STATUS_OKR_ZEROED_MASK    0X00000800

#define CSU_AES_STATUS_BOOT_ZEROED_SHIFT   10
#define CSU_AES_STATUS_BOOT_ZEROED_WIDTH   1
#define CSU_AES_STATUS_BOOT_ZEROED_MASK    0X00000400

#define CSU_AES_STATUS_KUP_ZEROED_SHIFT   9
#define CSU_AES_STATUS_KUP_ZEROED_WIDTH   1
#define CSU_AES_STATUS_KUP_ZEROED_MASK    0X00000200

#define CSU_AES_STATUS_AES_KEY_ZEROED_SHIFT   8
#define CSU_AES_STATUS_AES_KEY_ZEROED_WIDTH   1
#define CSU_AES_STATUS_AES_KEY_ZEROED_MASK    0X00000100

#define CSU_AES_STATUS_KEY_INIT_DONE_SHIFT   4
#define CSU_AES_STATUS_KEY_INIT_DONE_WIDTH   1
#define CSU_AES_STATUS_KEY_INIT_DONE_MASK    0X00000010

#define CSU_AES_STATUS_GCM_TAG_PASS_SHIFT   3
#define CSU_AES_STATUS_GCM_TAG_PASS_WIDTH   1
#define CSU_AES_STATUS_GCM_TAG_PASS_MASK    0X00000008

#define CSU_AES_STATUS_DONE_SHIFT   2
#define CSU_AES_STATUS_DONE_WIDTH   1
#define CSU_AES_STATUS_DONE_MASK    0X00000004

#define CSU_AES_STATUS_READY_SHIFT   1
#define CSU_AES_STATUS_READY_WIDTH   1
#define CSU_AES_STATUS_READY_MASK    0X00000002

#define CSU_AES_STATUS_BUSY_SHIFT   0
#define CSU_AES_STATUS_BUSY_WIDTH   1
#define CSU_AES_STATUS_BUSY_MASK    0X00000001

/**
 * Register: CSU_AES_KEY_SRC
 */
#define CSU_AES_KEY_SRC    ( ( CSU_BASEADDR ) + 0X00001004 )

#define CSU_AES_KEY_SRC_KEY_SRC_SHIFT   0
#define CSU_AES_KEY_SRC_KEY_SRC_WIDTH   4
#define CSU_AES_KEY_SRC_KEY_SRC_MASK    0X0000000F

/**
 * Register: CSU_AES_KEY_LOAD
 */
#define CSU_AES_KEY_LOAD    ( ( CSU_BASEADDR ) + 0X00001008 )

#define CSU_AES_KEY_LOAD_KEY_LOAD_SHIFT   0
#define CSU_AES_KEY_LOAD_KEY_LOAD_WIDTH   1
#define CSU_AES_KEY_LOAD_KEY_LOAD_MASK    0X00000001

/**
 * Register: CSU_AES_START_MSG
 */
#define CSU_AES_START_MSG    ( ( CSU_BASEADDR ) + 0X0000100C )

#define CSU_AES_START_MSG_START_MSG_SHIFT   0
#define CSU_AES_START_MSG_START_MSG_WIDTH   1
#define CSU_AES_START_MSG_START_MSG_MASK    0X00000001

/**
 * Register: CSU_AES_RESET
 */
#define CSU_AES_RESET    ( ( CSU_BASEADDR ) + 0X00001010 )

#define CSU_AES_RESET_RESET_SHIFT   0
#define CSU_AES_RESET_RESET_WIDTH   1
#define CSU_AES_RESET_RESET_MASK    0X00000001

/**
 * Register: CSU_AES_KEY_CLEAR
 */
#define CSU_AES_KEY_CLEAR    ( ( CSU_BASEADDR ) + 0X00001014 )

#define CSU_AES_KEY_CLEAR_AES_OKR_ZERO_SHIFT   3
#define CSU_AES_KEY_CLEAR_AES_OKR_ZERO_WIDTH   1
#define CSU_AES_KEY_CLEAR_AES_OKR_ZERO_MASK    0X00000008

#define CSU_AES_KEY_CLEAR_AES_BOOT_ZERO_SHIFT   2
#define CSU_AES_KEY_CLEAR_AES_BOOT_ZERO_WIDTH   1
#define CSU_AES_KEY_CLEAR_AES_BOOT_ZERO_MASK    0X00000004

#define CSU_AES_KEY_CLEAR_AES_KUP_ZERO_SHIFT   1
#define CSU_AES_KEY_CLEAR_AES_KUP_ZERO_WIDTH   1
#define CSU_AES_KEY_CLEAR_AES_KUP_ZERO_MASK    0X00000002

#define CSU_AES_KEY_CLEAR_AES_KEY_ZERO_SHIFT   0
#define CSU_AES_KEY_CLEAR_AES_KEY_ZERO_WIDTH   1
#define CSU_AES_KEY_CLEAR_AES_KEY_ZERO_MASK    0X00000001

/**
 * Register: CSU_AES_CFG
 */
#define CSU_AES_CFG    ( ( CSU_BASEADDR ) + 0X00001018 )

#define CSU_AES_CFG_ENCRYPT_DECRYPT_N_SHIFT   0
#define CSU_AES_CFG_ENCRYPT_DECRYPT_N_WIDTH   1
#define CSU_AES_CFG_ENCRYPT_DECRYPT_N_MASK    0X00000001

/**
 * Register: CSU_AES_KUP_WR
 */
#define CSU_AES_KUP_WR    ( ( CSU_BASEADDR ) + 0X0000101C )

#define CSU_AES_KUP_WR_IV_WRITE_SHIFT   1
#define CSU_AES_KUP_WR_IV_WRITE_WIDTH   1
#define CSU_AES_KUP_WR_IV_WRITE_MASK    0X00000002

#define CSU_AES_KUP_WR_KUP_WRITE_SHIFT   0
#define CSU_AES_KUP_WR_KUP_WRITE_WIDTH   1
#define CSU_AES_KUP_WR_KUP_WRITE_MASK    0X00000001

/**
 * Register: CSU_AES_KUP_0
 */
#define CSU_AES_KUP_0    ( ( CSU_BASEADDR ) + 0X00001020 )

#define CSU_AES_KUP_0_AES_KEY_SHIFT   0
#define CSU_AES_KUP_0_AES_KEY_WIDTH   32
#define CSU_AES_KUP_0_AES_KEY_MASK    0XFFFFFFFF

/**
 * Register: CSU_AES_KUP_1
 */
#define CSU_AES_KUP_1    ( ( CSU_BASEADDR ) + 0X00001024 )

#define CSU_AES_KUP_1_AES_KEY_SHIFT   0
#define CSU_AES_KUP_1_AES_KEY_WIDTH   32
#define CSU_AES_KUP_1_AES_KEY_MASK    0XFFFFFFFF

/**
 * Register: CSU_AES_KUP_2
 */
#define CSU_AES_KUP_2    ( ( CSU_BASEADDR ) + 0X00001028 )

#define CSU_AES_KUP_2_AES_KEY_SHIFT   0
#define CSU_AES_KUP_2_AES_KEY_WIDTH   32
#define CSU_AES_KUP_2_AES_KEY_MASK    0XFFFFFFFF

/**
 * Register: CSU_AES_KUP_3
 */
#define CSU_AES_KUP_3    ( ( CSU_BASEADDR ) + 0X0000102C )

#define CSU_AES_KUP_3_AES_KEY_SHIFT   0
#define CSU_AES_KUP_3_AES_KEY_WIDTH   32
#define CSU_AES_KUP_3_AES_KEY_MASK    0XFFFFFFFF

/**
 * Register: CSU_AES_KUP_4
 */
#define CSU_AES_KUP_4    ( ( CSU_BASEADDR ) + 0X00001030 )

#define CSU_AES_KUP_4_AES_KEY_SHIFT   0
#define CSU_AES_KUP_4_AES_KEY_WIDTH   32
#define CSU_AES_KUP_4_AES_KEY_MASK    0XFFFFFFFF

/**
 * Register: CSU_AES_KUP_5
 */
#define CSU_AES_KUP_5    ( ( CSU_BASEADDR ) + 0X00001034 )

#define CSU_AES_KUP_5_AES_KEY_SHIFT   0
#define CSU_AES_KUP_5_AES_KEY_WIDTH   32
#define CSU_AES_KUP_5_AES_KEY_MASK    0XFFFFFFFF

/**
 * Register: CSU_AES_KUP_6
 */
#define CSU_AES_KUP_6    ( ( CSU_BASEADDR ) + 0X00001038 )

#define CSU_AES_KUP_6_AES_KEY_SHIFT   0
#define CSU_AES_KUP_6_AES_KEY_WIDTH   32
#define CSU_AES_KUP_6_AES_KEY_MASK    0XFFFFFFFF

/**
 * Register: CSU_AES_KUP_7
 */
#define CSU_AES_KUP_7    ( ( CSU_BASEADDR ) + 0X0000103C )

#define CSU_AES_KUP_7_AES_KEY_SHIFT   0
#define CSU_AES_KUP_7_AES_KEY_WIDTH   32
#define CSU_AES_KUP_7_AES_KEY_MASK    0XFFFFFFFF

/**
 * Register: CSU_AES_IV_0
 */
#define CSU_AES_IV_0    ( ( CSU_BASEADDR ) + 0X00001040 )

#define CSU_AES_IV_0_AES_IV_SHIFT   0
#define CSU_AES_IV_0_AES_IV_WIDTH   32
#define CSU_AES_IV_0_AES_IV_MASK    0XFFFFFFFF

/**
 * Register: CSU_AES_IV_1
 */
#define CSU_AES_IV_1    ( ( CSU_BASEADDR ) + 0X00001044 )

#define CSU_AES_IV_1_AES_IV_SHIFT   0
#define CSU_AES_IV_1_AES_IV_WIDTH   32
#define CSU_AES_IV_1_AES_IV_MASK    0XFFFFFFFF

/**
 * Register: CSU_AES_IV_2
 */
#define CSU_AES_IV_2    ( ( CSU_BASEADDR ) + 0X00001048 )

#define CSU_AES_IV_2_AES_IV_SHIFT   0
#define CSU_AES_IV_2_AES_IV_WIDTH   32
#define CSU_AES_IV_2_AES_IV_MASK    0XFFFFFFFF

/**
 * Register: CSU_AES_IV_3
 */
#define CSU_AES_IV_3    ( ( CSU_BASEADDR ) + 0X0000104C )

#define CSU_AES_IV_3_AES_IV_DLC_SHIFT   0
#define CSU_AES_IV_3_AES_IV_DLC_WIDTH   32
#define CSU_AES_IV_3_AES_IV_DLC_MASK    0XFFFFFFFF

/**
 * Register: CSU_SHA_START
 */
#define CSU_SHA_START    ( ( CSU_BASEADDR ) + 0X00002000 )

#define CSU_SHA_START_START_MSG_SHIFT   0
#define CSU_SHA_START_START_MSG_WIDTH   1
#define CSU_SHA_START_START_MSG_MASK    0X00000001

/**
 * Register: CSU_SHA_RESET
 */
#define CSU_SHA_RESET    ( ( CSU_BASEADDR ) + 0X00002004 )

#define CSU_SHA_RESET_RESET_SHIFT   0
#define CSU_SHA_RESET_RESET_WIDTH   1
#define CSU_SHA_RESET_RESET_MASK    0X00000001

/**
 * Register: CSU_SHA_DONE
 */
#define CSU_SHA_DONE    ( ( CSU_BASEADDR ) + 0X00002008 )

#define CSU_SHA_DONE_SHA_DONE_SHIFT   0
#define CSU_SHA_DONE_SHA_DONE_WIDTH   1
#define CSU_SHA_DONE_SHA_DONE_MASK    0X00000001

/**
 * Register: CSU_SHA_DIGEST_0
 */
#define CSU_SHA_DIGEST_0    ( ( CSU_BASEADDR ) + 0X00002010 )

#define CSU_SHA_DIGEST_0_DIGEST_SHIFT   0
#define CSU_SHA_DIGEST_0_DIGEST_WIDTH   32
#define CSU_SHA_DIGEST_0_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_SHA_DIGEST_1
 */
#define CSU_SHA_DIGEST_1    ( ( CSU_BASEADDR ) + 0X00002014 )

#define CSU_SHA_DIGEST_1_DIGEST_SHIFT   0
#define CSU_SHA_DIGEST_1_DIGEST_WIDTH   32
#define CSU_SHA_DIGEST_1_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_SHA_DIGEST_2
 */
#define CSU_SHA_DIGEST_2    ( ( CSU_BASEADDR ) + 0X00002018 )

#define CSU_SHA_DIGEST_2_DIGEST_SHIFT   0
#define CSU_SHA_DIGEST_2_DIGEST_WIDTH   32
#define CSU_SHA_DIGEST_2_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_SHA_DIGEST_3
 */
#define CSU_SHA_DIGEST_3    ( ( CSU_BASEADDR ) + 0X0000201C )

#define CSU_SHA_DIGEST_3_DIGEST_SHIFT   0
#define CSU_SHA_DIGEST_3_DIGEST_WIDTH   32
#define CSU_SHA_DIGEST_3_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_SHA_DIGEST_4
 */
#define CSU_SHA_DIGEST_4    ( ( CSU_BASEADDR ) + 0X00002020 )

#define CSU_SHA_DIGEST_4_DIGEST_SHIFT   0
#define CSU_SHA_DIGEST_4_DIGEST_WIDTH   32
#define CSU_SHA_DIGEST_4_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_SHA_DIGEST_5
 */
#define CSU_SHA_DIGEST_5    ( ( CSU_BASEADDR ) + 0X00002024 )

#define CSU_SHA_DIGEST_5_DIGEST_SHIFT   0
#define CSU_SHA_DIGEST_5_DIGEST_WIDTH   32
#define CSU_SHA_DIGEST_5_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_SHA_DIGEST_6
 */
#define CSU_SHA_DIGEST_6    ( ( CSU_BASEADDR ) + 0X00002028 )

#define CSU_SHA_DIGEST_6_DIGEST_SHIFT   0
#define CSU_SHA_DIGEST_6_DIGEST_WIDTH   32
#define CSU_SHA_DIGEST_6_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_SHA_DIGEST_7
 */
#define CSU_SHA_DIGEST_7    ( ( CSU_BASEADDR ) + 0X0000202C )

#define CSU_SHA_DIGEST_7_DIGEST_SHIFT   0
#define CSU_SHA_DIGEST_7_DIGEST_WIDTH   32
#define CSU_SHA_DIGEST_7_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_SHA_DIGEST_8
 */
#define CSU_SHA_DIGEST_8    ( ( CSU_BASEADDR ) + 0X00002030 )

#define CSU_SHA_DIGEST_8_DIGEST_SHIFT   0
#define CSU_SHA_DIGEST_8_DIGEST_WIDTH   32
#define CSU_SHA_DIGEST_8_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_SHA_DIGEST_9
 */
#define CSU_SHA_DIGEST_9    ( ( CSU_BASEADDR ) + 0X00002034 )

#define CSU_SHA_DIGEST_9_DIGEST_SHIFT   0
#define CSU_SHA_DIGEST_9_DIGEST_WIDTH   32
#define CSU_SHA_DIGEST_9_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_SHA_DIGEST_10
 */
#define CSU_SHA_DIGEST_10    ( ( CSU_BASEADDR ) + 0X00002038 )

#define CSU_SHA_DIGEST_10_DIGEST_SHIFT   0
#define CSU_SHA_DIGEST_10_DIGEST_WIDTH   32
#define CSU_SHA_DIGEST_10_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_SHA_DIGEST_11
 */
#define CSU_SHA_DIGEST_11    ( ( CSU_BASEADDR ) + 0X0000203C )

#define CSU_SHA_DIGEST_11_DIGEST_SHIFT   0
#define CSU_SHA_DIGEST_11_DIGEST_WIDTH   32
#define CSU_SHA_DIGEST_11_DIGEST_MASK    0XFFFFFFFF

/**
 * Register: CSU_PCAP_PROG
 */
#define CSU_PCAP_PROG    ( ( CSU_BASEADDR ) + 0X00003000 )

#define CSU_PCAP_PROG_PCFG_PROG_B_SHIFT   0
#define CSU_PCAP_PROG_PCFG_PROG_B_WIDTH   1
#define CSU_PCAP_PROG_PCFG_PROG_B_MASK    0X00000001

/**
 * Register: CSU_PCAP_RDWR
 */
#define CSU_PCAP_RDWR    ( ( CSU_BASEADDR ) + 0X00003004 )

#define CSU_PCAP_RDWR_PCAP_RDWR_B_SHIFT   0
#define CSU_PCAP_RDWR_PCAP_RDWR_B_WIDTH   1
#define CSU_PCAP_RDWR_PCAP_RDWR_B_MASK    0X00000001

/**
 * Register: CSU_PCAP_CTRL
 */
#define CSU_PCAP_CTRL    ( ( CSU_BASEADDR ) + 0X00003008 )

#define CSU_PCAP_CTRL_PCFG_GSR_SHIFT   3
#define CSU_PCAP_CTRL_PCFG_GSR_WIDTH   1
#define CSU_PCAP_CTRL_PCFG_GSR_MASK    0X00000008

#define CSU_PCAP_CTRL_PCFG_GTS_SHIFT   2
#define CSU_PCAP_CTRL_PCFG_GTS_WIDTH   1
#define CSU_PCAP_CTRL_PCFG_GTS_MASK    0X00000004

#define CSU_PCAP_CTRL_PCFG_POR_CNT_4K_SHIFT   1
#define CSU_PCAP_CTRL_PCFG_POR_CNT_4K_WIDTH   1
#define CSU_PCAP_CTRL_PCFG_POR_CNT_4K_MASK    0X00000002

#define CSU_PCAP_CTRL_PCAP_PR_SHIFT   0
#define CSU_PCAP_CTRL_PCAP_PR_WIDTH   1
#define CSU_PCAP_CTRL_PCAP_PR_MASK    0X00000001

/**
 * Register: CSU_PCAP_RESET
 */
#define CSU_PCAP_RESET    ( ( CSU_BASEADDR ) + 0X0000300C )

#define CSU_PCAP_RESET_RESET_SHIFT   0
#define CSU_PCAP_RESET_RESET_WIDTH   1
#define CSU_PCAP_RESET_RESET_MASK    0X00000001

/**
 * Register: CSU_PCAP_STATUS
 */
#define CSU_PCAP_STATUS    ( ( CSU_BASEADDR ) + 0X00003010 )

#define CSU_PCAP_STATUS_PL_GTS_USR_B_SHIFT   11
#define CSU_PCAP_STATUS_PL_GTS_USR_B_WIDTH   1
#define CSU_PCAP_STATUS_PL_GTS_USR_B_MASK    0X00000800

#define CSU_PCAP_STATUS_PL_GTS_CFG_B_SHIFT   10
#define CSU_PCAP_STATUS_PL_GTS_CFG_B_WIDTH   1
#define CSU_PCAP_STATUS_PL_GTS_CFG_B_MASK    0X00000400

#define CSU_PCAP_STATUS_PL_GPWRDWN_B_SHIFT   9
#define CSU_PCAP_STATUS_PL_GPWRDWN_B_WIDTH   1
#define CSU_PCAP_STATUS_PL_GPWRDWN_B_MASK    0X00000200

#define CSU_PCAP_STATUS_PL_GHIGH_B_SHIFT   8
#define CSU_PCAP_STATUS_PL_GHIGH_B_WIDTH   1
#define CSU_PCAP_STATUS_PL_GHIGH_B_MASK    0X00000100

#define CSU_PCAP_STATUS_PL_FST_CFG_SHIFT   7
#define CSU_PCAP_STATUS_PL_FST_CFG_WIDTH   1
#define CSU_PCAP_STATUS_PL_FST_CFG_MASK    0X00000080

#define CSU_PCAP_STATUS_PL_CFG_RESET_B_SHIFT   6
#define CSU_PCAP_STATUS_PL_CFG_RESET_B_WIDTH   1
#define CSU_PCAP_STATUS_PL_CFG_RESET_B_MASK    0X00000040

#define CSU_PCAP_STATUS_PL_SEU_ERROR_SHIFT   5
#define CSU_PCAP_STATUS_PL_SEU_ERROR_WIDTH   1
#define CSU_PCAP_STATUS_PL_SEU_ERROR_MASK    0X00000020

#define CSU_PCAP_STATUS_PL_EOS_SHIFT   4
#define CSU_PCAP_STATUS_PL_EOS_WIDTH   1
#define CSU_PCAP_STATUS_PL_EOS_MASK    0X00000010

#define CSU_PCAP_STATUS_PL_DONE_SHIFT   3
#define CSU_PCAP_STATUS_PL_DONE_WIDTH   1
#define CSU_PCAP_STATUS_PL_DONE_MASK    0X00000008

#define CSU_PCAP_STATUS_PL_INIT_SHIFT   2
#define CSU_PCAP_STATUS_PL_INIT_WIDTH   1
#define CSU_PCAP_STATUS_PL_INIT_MASK    0X00000004

#define CSU_PCAP_STATUS_PCAP_RD_IDLE_SHIFT   1
#define CSU_PCAP_STATUS_PCAP_RD_IDLE_WIDTH   1
#define CSU_PCAP_STATUS_PCAP_RD_IDLE_MASK    0X00000002

#define CSU_PCAP_STATUS_PCAP_WR_IDLE_SHIFT   0
#define CSU_PCAP_STATUS_PCAP_WR_IDLE_WIDTH   1
#define CSU_PCAP_STATUS_PCAP_WR_IDLE_MASK    0X00000001

/**
 * Register: CSU_COMMAND
 */
#define CSU_COMMAND    ( ( CSU_BASEADDR ) + 0X00004000 )

#define CSU_COMMAND_CMD_SHIFT   0
#define CSU_COMMAND_CMD_WIDTH   4
#define CSU_COMMAND_CMD_MASK    0X0000000F

/**
 * Register: CSU_CFG0
 */
#define CSU_CFG0    ( ( CSU_BASEADDR ) + 0X00004004 )

#define CSU_CFG0_CFG0_SHIFT   0
#define CSU_CFG0_CFG0_WIDTH   32
#define CSU_CFG0_CFG0_MASK    0XFFFFFFFF

/**
 * Register: CSU_CFG1
 */
#define CSU_CFG1    ( ( CSU_BASEADDR ) + 0X00004008 )

#define CSU_CFG1_CFG1_SHIFT   0
#define CSU_CFG1_CFG1_WIDTH   32
#define CSU_CFG1_CFG1_MASK    0XFFFFFFFF

/**
 * Register: CSU_CFG2
 */
#define CSU_CFG2    ( ( CSU_BASEADDR ) + 0X0000400C )

#define CSU_CFG2_CFG2_SHIFT   0
#define CSU_CFG2_CFG2_WIDTH   32
#define CSU_CFG2_CFG2_MASK    0XFFFFFFFF

/**
 * Register: CSU_STATUS
 */
#define CSU_STATUS    ( ( CSU_BASEADDR ) + 0X00004010 )

#define CSU_STATUS_KR_SHIFT   3
#define CSU_STATUS_KR_WIDTH   1
#define CSU_STATUS_KR_MASK    0X00000008

#define CSU_STATUS_ZZ_SHIFT   1
#define CSU_STATUS_ZZ_WIDTH   1
#define CSU_STATUS_ZZ_MASK    0X00000002

#define CSU_STATUS_WR_SHIFT   0
#define CSU_STATUS_WR_WIDTH   1
#define CSU_STATUS_WR_MASK    0X00000001

/**
 * Register: CSU_SYN_WORD
 */
#define CSU_SYN_WORD    ( ( CSU_BASEADDR ) + 0X00004014 )

#define CSU_SYN_WORD_SYN_SHIFT   0
#define CSU_SYN_WORD_SYN_WIDTH   32
#define CSU_SYN_WORD_SYN_MASK    0XFFFFFFFF

/**
 * Register: CSU_CHASH
 */
#define CSU_CHASH    ( ( CSU_BASEADDR ) + 0X00004018 )

#define CSU_CHASH_CHASH_SHIFT   0
#define CSU_CHASH_CHASH_WIDTH   32
#define CSU_CHASH_CHASH_MASK    0XFFFFFFFF

/**
 * Register: CSU_TM_STATUS
 */
#define CSU_TM_STATUS    ( ( CSU_BASEADDR ) + 0X00004804 )

#define CSU_TM_STATUS_DN_SHIFT   0
#define CSU_TM_STATUS_DN_WIDTH   1
#define CSU_TM_STATUS_DN_MASK    0X00000001

/**
 * Register: CSU_TM_UL
 */
#define CSU_TM_UL    ( ( CSU_BASEADDR ) + 0X00004808 )

#define CSU_TM_UL_UL_SHIFT   0
#define CSU_TM_UL_UL_WIDTH   18
#define CSU_TM_UL_UL_MASK    0X0003FFFF

/**
 * Register: CSU_TM_LL
 */
#define CSU_TM_LL    ( ( CSU_BASEADDR ) + 0X0000480C )

#define CSU_TM_LL_LL_SHIFT   0
#define CSU_TM_LL_LL_WIDTH   18
#define CSU_TM_LL_LL_MASK    0X0003FFFF

/**
 * Register: CSU_TM_SW
 */
#define CSU_TM_SW    ( ( CSU_BASEADDR ) + 0X00004810 )

#define CSU_TM_SW_OFF_SHIFT   24
#define CSU_TM_SW_OFF_WIDTH   8
#define CSU_TM_SW_OFF_MASK    0XFF000000

#define CSU_TM_SW_SW_SHIFT   0
#define CSU_TM_SW_SW_WIDTH   24
#define CSU_TM_SW_SW_MASK    0X00FFFFFF

/**
 * Register: CSU_TM_TR
 */
#define CSU_TM_TR    ( ( CSU_BASEADDR ) + 0X00004814 )

#define CSU_TM_TR_US_SHIFT   24
#define CSU_TM_TR_US_WIDTH   2
#define CSU_TM_TR_US_MASK    0X03000000

#define CSU_TM_TR_ER_SHIFT   16
#define CSU_TM_TR_ER_WIDTH   8
#define CSU_TM_TR_ER_MASK    0X00FF0000

#define CSU_TM_TR_FRR_SHIFT   0
#define CSU_TM_TR_FRR_WIDTH   1
#define CSU_TM_TR_FRR_MASK    0X00000001

/**
 * Register: CSU_TM_RAW
 */
#define CSU_TM_RAW    ( ( CSU_BASEADDR ) + 0X00004818 )

#define CSU_TM_RAW_RAW_SHIFT   0
#define CSU_TM_RAW_RAW_WIDTH   32
#define CSU_TM_RAW_RAW_MASK    0XFFFFFFFF

/**
 * Register: CSU_CSU_TAMPER_0
 */
#define CSU_CSU_TAMPER_0    ( ( CSU_BASEADDR ) + 0X00005000 )

#define CSU_CSU_TAMPER_0_BBRAM_ERASE_SHIFT   4
#define CSU_CSU_TAMPER_0_BBRAM_ERASE_WIDTH   1
#define CSU_CSU_TAMPER_0_BBRAM_ERASE_MASK    0X00000010

#define CSU_CSU_TAMPER_0_SEC_LOCKDOWN_1_SHIFT   3
#define CSU_CSU_TAMPER_0_SEC_LOCKDOWN_1_WIDTH   1
#define CSU_CSU_TAMPER_0_SEC_LOCKDOWN_1_MASK    0X00000008

#define CSU_CSU_TAMPER_0_SEC_LOCKDOWN_0_SHIFT   2
#define CSU_CSU_TAMPER_0_SEC_LOCKDOWN_0_WIDTH   1
#define CSU_CSU_TAMPER_0_SEC_LOCKDOWN_0_MASK    0X00000004

#define CSU_CSU_TAMPER_0_SYS_RESET_SHIFT   1
#define CSU_CSU_TAMPER_0_SYS_RESET_WIDTH   1
#define CSU_CSU_TAMPER_0_SYS_RESET_MASK    0X00000002

#define CSU_CSU_TAMPER_0_SYS_INTERRUPT_SHIFT   0
#define CSU_CSU_TAMPER_0_SYS_INTERRUPT_WIDTH   1
#define CSU_CSU_TAMPER_0_SYS_INTERRUPT_MASK    0X00000001

/**
 * Register: CSU_CSU_TAMPER_1
 */
#define CSU_CSU_TAMPER_1    ( ( CSU_BASEADDR ) + 0X00005004 )

#define CSU_CSU_TAMPER_1_BBRAM_ERASE_SHIFT   4
#define CSU_CSU_TAMPER_1_BBRAM_ERASE_WIDTH   1
#define CSU_CSU_TAMPER_1_BBRAM_ERASE_MASK    0X00000010

#define CSU_CSU_TAMPER_1_SEC_LOCKDOWN_1_SHIFT   3
#define CSU_CSU_TAMPER_1_SEC_LOCKDOWN_1_WIDTH   1
#define CSU_CSU_TAMPER_1_SEC_LOCKDOWN_1_MASK    0X00000008

#define CSU_CSU_TAMPER_1_SEC_LOCKDOWN_0_SHIFT   2
#define CSU_CSU_TAMPER_1_SEC_LOCKDOWN_0_WIDTH   1
#define CSU_CSU_TAMPER_1_SEC_LOCKDOWN_0_MASK    0X00000004

#define CSU_CSU_TAMPER_1_SYS_RESET_SHIFT   1
#define CSU_CSU_TAMPER_1_SYS_RESET_WIDTH   1
#define CSU_CSU_TAMPER_1_SYS_RESET_MASK    0X00000002

#define CSU_CSU_TAMPER_1_SYS_INTERRUPT_SHIFT   0
#define CSU_CSU_TAMPER_1_SYS_INTERRUPT_WIDTH   1
#define CSU_CSU_TAMPER_1_SYS_INTERRUPT_MASK    0X00000001

/**
 * Register: CSU_CSU_TAMPER_2
 */
#define CSU_CSU_TAMPER_2    ( ( CSU_BASEADDR ) + 0X00005008 )

#define CSU_CSU_TAMPER_2_BBRAM_ERASE_SHIFT   4
#define CSU_CSU_TAMPER_2_BBRAM_ERASE_WIDTH   1
#define CSU_CSU_TAMPER_2_BBRAM_ERASE_MASK    0X00000010

#define CSU_CSU_TAMPER_2_SEC_LOCKDOWN_1_SHIFT   3
#define CSU_CSU_TAMPER_2_SEC_LOCKDOWN_1_WIDTH   1
#define CSU_CSU_TAMPER_2_SEC_LOCKDOWN_1_MASK    0X00000008

#define CSU_CSU_TAMPER_2_SEC_LOCKDOWN_0_SHIFT   2
#define CSU_CSU_TAMPER_2_SEC_LOCKDOWN_0_WIDTH   1
#define CSU_CSU_TAMPER_2_SEC_LOCKDOWN_0_MASK    0X00000004

#define CSU_CSU_TAMPER_2_SYS_RESET_SHIFT   1
#define CSU_CSU_TAMPER_2_SYS_RESET_WIDTH   1
#define CSU_CSU_TAMPER_2_SYS_RESET_MASK    0X00000002

#define CSU_CSU_TAMPER_2_SYS_INTERRUPT_SHIFT   0
#define CSU_CSU_TAMPER_2_SYS_INTERRUPT_WIDTH   1
#define CSU_CSU_TAMPER_2_SYS_INTERRUPT_MASK    0X00000001

/**
 * Register: CSU_CSU_TAMPER_3
 */
#define CSU_CSU_TAMPER_3    ( ( CSU_BASEADDR ) + 0X0000500C )

#define CSU_CSU_TAMPER_3_BBRAM_ERASE_SHIFT   4
#define CSU_CSU_TAMPER_3_BBRAM_ERASE_WIDTH   1
#define CSU_CSU_TAMPER_3_BBRAM_ERASE_MASK    0X00000010

#define CSU_CSU_TAMPER_3_SEC_LOCKDOWN_1_SHIFT   3
#define CSU_CSU_TAMPER_3_SEC_LOCKDOWN_1_WIDTH   1
#define CSU_CSU_TAMPER_3_SEC_LOCKDOWN_1_MASK    0X00000008

#define CSU_CSU_TAMPER_3_SEC_LOCKDOWN_0_SHIFT   2
#define CSU_CSU_TAMPER_3_SEC_LOCKDOWN_0_WIDTH   1
#define CSU_CSU_TAMPER_3_SEC_LOCKDOWN_0_MASK    0X00000004

#define CSU_CSU_TAMPER_3_SYS_RESET_SHIFT   1
#define CSU_CSU_TAMPER_3_SYS_RESET_WIDTH   1
#define CSU_CSU_TAMPER_3_SYS_RESET_MASK    0X00000002

#define CSU_CSU_TAMPER_3_SYS_INTERRUPT_SHIFT   0
#define CSU_CSU_TAMPER_3_SYS_INTERRUPT_WIDTH   1
#define CSU_CSU_TAMPER_3_SYS_INTERRUPT_MASK    0X00000001

/**
 * Register: CSU_CSU_TAMPER_4
 */
#define CSU_CSU_TAMPER_4    ( ( CSU_BASEADDR ) + 0X00005010 )

#define CSU_CSU_TAMPER_4_BBRAM_ERASE_SHIFT   4
#define CSU_CSU_TAMPER_4_BBRAM_ERASE_WIDTH   1
#define CSU_CSU_TAMPER_4_BBRAM_ERASE_MASK    0X00000010

#define CSU_CSU_TAMPER_4_SEC_LOCKDOWN_1_SHIFT   3
#define CSU_CSU_TAMPER_4_SEC_LOCKDOWN_1_WIDTH   1
#define CSU_CSU_TAMPER_4_SEC_LOCKDOWN_1_MASK    0X00000008

#define CSU_CSU_TAMPER_4_SEC_LOCKDOWN_0_SHIFT   2
#define CSU_CSU_TAMPER_4_SEC_LOCKDOWN_0_WIDTH   1
#define CSU_CSU_TAMPER_4_SEC_LOCKDOWN_0_MASK    0X00000004

#define CSU_CSU_TAMPER_4_SYS_RESET_SHIFT   1
#define CSU_CSU_TAMPER_4_SYS_RESET_WIDTH   1
#define CSU_CSU_TAMPER_4_SYS_RESET_MASK    0X00000002

#define CSU_CSU_TAMPER_4_SYS_INTERRUPT_SHIFT   0
#define CSU_CSU_TAMPER_4_SYS_INTERRUPT_WIDTH   1
#define CSU_CSU_TAMPER_4_SYS_INTERRUPT_MASK    0X00000001

/**
 * Register: CSU_CSU_TAMPER_5
 */
#define CSU_CSU_TAMPER_5    ( ( CSU_BASEADDR ) + 0X00005014 )

#define CSU_CSU_TAMPER_5_BBRAM_ERASE_SHIFT   4
#define CSU_CSU_TAMPER_5_BBRAM_ERASE_WIDTH   1
#define CSU_CSU_TAMPER_5_BBRAM_ERASE_MASK    0X00000010

#define CSU_CSU_TAMPER_5_SEC_LOCKDOWN_1_SHIFT   3
#define CSU_CSU_TAMPER_5_SEC_LOCKDOWN_1_WIDTH   1
#define CSU_CSU_TAMPER_5_SEC_LOCKDOWN_1_MASK    0X00000008

#define CSU_CSU_TAMPER_5_SEC_LOCKDOWN_0_SHIFT   2
#define CSU_CSU_TAMPER_5_SEC_LOCKDOWN_0_WIDTH   1
#define CSU_CSU_TAMPER_5_SEC_LOCKDOWN_0_MASK    0X00000004

#define CSU_CSU_TAMPER_5_SYS_RESET_SHIFT   1
#define CSU_CSU_TAMPER_5_SYS_RESET_WIDTH   1
#define CSU_CSU_TAMPER_5_SYS_RESET_MASK    0X00000002

#define CSU_CSU_TAMPER_5_SYS_INTERRUPT_SHIFT   0
#define CSU_CSU_TAMPER_5_SYS_INTERRUPT_WIDTH   1
#define CSU_CSU_TAMPER_5_SYS_INTERRUPT_MASK    0X00000001

/**
 * Register: CSU_CSU_TAMPER_6
 */
#define CSU_CSU_TAMPER_6    ( ( CSU_BASEADDR ) + 0X00005018 )

#define CSU_CSU_TAMPER_6_BBRAM_ERASE_SHIFT   4
#define CSU_CSU_TAMPER_6_BBRAM_ERASE_WIDTH   1
#define CSU_CSU_TAMPER_6_BBRAM_ERASE_MASK    0X00000010

#define CSU_CSU_TAMPER_6_SEC_LOCKDOWN_1_SHIFT   3
#define CSU_CSU_TAMPER_6_SEC_LOCKDOWN_1_WIDTH   1
#define CSU_CSU_TAMPER_6_SEC_LOCKDOWN_1_MASK    0X00000008

#define CSU_CSU_TAMPER_6_SEC_LOCKDOWN_0_SHIFT   2
#define CSU_CSU_TAMPER_6_SEC_LOCKDOWN_0_WIDTH   1
#define CSU_CSU_TAMPER_6_SEC_LOCKDOWN_0_MASK    0X00000004

#define CSU_CSU_TAMPER_6_SYS_RESET_SHIFT   1
#define CSU_CSU_TAMPER_6_SYS_RESET_WIDTH   1
#define CSU_CSU_TAMPER_6_SYS_RESET_MASK    0X00000002

#define CSU_CSU_TAMPER_6_SYS_INTERRUPT_SHIFT   0
#define CSU_CSU_TAMPER_6_SYS_INTERRUPT_WIDTH   1
#define CSU_CSU_TAMPER_6_SYS_INTERRUPT_MASK    0X00000001

/**
 * Register: CSU_CSU_TAMPER_7
 */
#define CSU_CSU_TAMPER_7    ( ( CSU_BASEADDR ) + 0X0000501C )

#define CSU_CSU_TAMPER_7_BBRAM_ERASE_SHIFT   4
#define CSU_CSU_TAMPER_7_BBRAM_ERASE_WIDTH   1
#define CSU_CSU_TAMPER_7_BBRAM_ERASE_MASK    0X00000010

#define CSU_CSU_TAMPER_7_SEC_LOCKDOWN_1_SHIFT   3
#define CSU_CSU_TAMPER_7_SEC_LOCKDOWN_1_WIDTH   1
#define CSU_CSU_TAMPER_7_SEC_LOCKDOWN_1_MASK    0X00000008

#define CSU_CSU_TAMPER_7_SEC_LOCKDOWN_0_SHIFT   2
#define CSU_CSU_TAMPER_7_SEC_LOCKDOWN_0_WIDTH   1
#define CSU_CSU_TAMPER_7_SEC_LOCKDOWN_0_MASK    0X00000004

#define CSU_CSU_TAMPER_7_SYS_RESET_SHIFT   1
#define CSU_CSU_TAMPER_7_SYS_RESET_WIDTH   1
#define CSU_CSU_TAMPER_7_SYS_RESET_MASK    0X00000002

#define CSU_CSU_TAMPER_7_SYS_INTERRUPT_SHIFT   0
#define CSU_CSU_TAMPER_7_SYS_INTERRUPT_WIDTH   1
#define CSU_CSU_TAMPER_7_SYS_INTERRUPT_MASK    0X00000001

/**
 * Register: CSU_CSU_TAMPER_8
 */
#define CSU_CSU_TAMPER_8    ( ( CSU_BASEADDR ) + 0X00005020 )

#define CSU_CSU_TAMPER_8_BBRAM_ERASE_SHIFT   4
#define CSU_CSU_TAMPER_8_BBRAM_ERASE_WIDTH   1
#define CSU_CSU_TAMPER_8_BBRAM_ERASE_MASK    0X00000010

#define CSU_CSU_TAMPER_8_SEC_LOCKDOWN_1_SHIFT   3
#define CSU_CSU_TAMPER_8_SEC_LOCKDOWN_1_WIDTH   1
#define CSU_CSU_TAMPER_8_SEC_LOCKDOWN_1_MASK    0X00000008

#define CSU_CSU_TAMPER_8_SEC_LOCKDOWN_0_SHIFT   2
#define CSU_CSU_TAMPER_8_SEC_LOCKDOWN_0_WIDTH   1
#define CSU_CSU_TAMPER_8_SEC_LOCKDOWN_0_MASK    0X00000004

#define CSU_CSU_TAMPER_8_SYS_RESET_SHIFT   1
#define CSU_CSU_TAMPER_8_SYS_RESET_WIDTH   1
#define CSU_CSU_TAMPER_8_SYS_RESET_MASK    0X00000002

#define CSU_CSU_TAMPER_8_SYS_INTERRUPT_SHIFT   0
#define CSU_CSU_TAMPER_8_SYS_INTERRUPT_WIDTH   1
#define CSU_CSU_TAMPER_8_SYS_INTERRUPT_MASK    0X00000001

/**
 * Register: CSU_CSU_TAMPER_9
 */
#define CSU_CSU_TAMPER_9    ( ( CSU_BASEADDR ) + 0X00005024 )

#define CSU_CSU_TAMPER_9_BBRAM_ERASE_SHIFT   4
#define CSU_CSU_TAMPER_9_BBRAM_ERASE_WIDTH   1
#define CSU_CSU_TAMPER_9_BBRAM_ERASE_MASK    0X00000010

#define CSU_CSU_TAMPER_9_SEC_LOCKDOWN_1_SHIFT   3
#define CSU_CSU_TAMPER_9_SEC_LOCKDOWN_1_WIDTH   1
#define CSU_CSU_TAMPER_9_SEC_LOCKDOWN_1_MASK    0X00000008

#define CSU_CSU_TAMPER_9_SEC_LOCKDOWN_0_SHIFT   2
#define CSU_CSU_TAMPER_9_SEC_LOCKDOWN_0_WIDTH   1
#define CSU_CSU_TAMPER_9_SEC_LOCKDOWN_0_MASK    0X00000004

#define CSU_CSU_TAMPER_9_SYS_RESET_SHIFT   1
#define CSU_CSU_TAMPER_9_SYS_RESET_WIDTH   1
#define CSU_CSU_TAMPER_9_SYS_RESET_MASK    0X00000002

#define CSU_CSU_TAMPER_9_SYS_INTERRUPT_SHIFT   0
#define CSU_CSU_TAMPER_9_SYS_INTERRUPT_WIDTH   1
#define CSU_CSU_TAMPER_9_SYS_INTERRUPT_MASK    0X00000001

/**
 * Register: CSU_CSU_TAMPER_10
 */
#define CSU_CSU_TAMPER_10    ( ( CSU_BASEADDR ) + 0X00005028 )

#define CSU_CSU_TAMPER_10_BBRAM_ERASE_SHIFT   4
#define CSU_CSU_TAMPER_10_BBRAM_ERASE_WIDTH   1
#define CSU_CSU_TAMPER_10_BBRAM_ERASE_MASK    0X00000010

#define CSU_CSU_TAMPER_10_SEC_LOCKDOWN_1_SHIFT   3
#define CSU_CSU_TAMPER_10_SEC_LOCKDOWN_1_WIDTH   1
#define CSU_CSU_TAMPER_10_SEC_LOCKDOWN_1_MASK    0X00000008

#define CSU_CSU_TAMPER_10_SEC_LOCKDOWN_0_SHIFT   2
#define CSU_CSU_TAMPER_10_SEC_LOCKDOWN_0_WIDTH   1
#define CSU_CSU_TAMPER_10_SEC_LOCKDOWN_0_MASK    0X00000004

#define CSU_CSU_TAMPER_10_SYS_RESET_SHIFT   1
#define CSU_CSU_TAMPER_10_SYS_RESET_WIDTH   1
#define CSU_CSU_TAMPER_10_SYS_RESET_MASK    0X00000002

#define CSU_CSU_TAMPER_10_SYS_INTERRUPT_SHIFT   0
#define CSU_CSU_TAMPER_10_SYS_INTERRUPT_WIDTH   1
#define CSU_CSU_TAMPER_10_SYS_INTERRUPT_MASK    0X00000001

/**
 * Register: CSU_CSU_TAMPER_11
 */
#define CSU_CSU_TAMPER_11    ( ( CSU_BASEADDR ) + 0X0000502C )

#define CSU_CSU_TAMPER_11_BBRAM_ERASE_SHIFT   4
#define CSU_CSU_TAMPER_11_BBRAM_ERASE_WIDTH   1
#define CSU_CSU_TAMPER_11_BBRAM_ERASE_MASK    0X00000010

#define CSU_CSU_TAMPER_11_SEC_LOCKDOWN_1_SHIFT   3
#define CSU_CSU_TAMPER_11_SEC_LOCKDOWN_1_WIDTH   1
#define CSU_CSU_TAMPER_11_SEC_LOCKDOWN_1_MASK    0X00000008

#define CSU_CSU_TAMPER_11_SEC_LOCKDOWN_0_SHIFT   2
#define CSU_CSU_TAMPER_11_SEC_LOCKDOWN_0_WIDTH   1
#define CSU_CSU_TAMPER_11_SEC_LOCKDOWN_0_MASK    0X00000004

#define CSU_CSU_TAMPER_11_SYS_RESET_SHIFT   1
#define CSU_CSU_TAMPER_11_SYS_RESET_WIDTH   1
#define CSU_CSU_TAMPER_11_SYS_RESET_MASK    0X00000002

#define CSU_CSU_TAMPER_11_SYS_INTERRUPT_SHIFT   0
#define CSU_CSU_TAMPER_11_SYS_INTERRUPT_WIDTH   1
#define CSU_CSU_TAMPER_11_SYS_INTERRUPT_MASK    0X00000001

/**
 * Register: CSU_CSU_TAMPER_12
 */
#define CSU_CSU_TAMPER_12    ( ( CSU_BASEADDR ) + 0X00005030 )

#define CSU_CSU_TAMPER_12_BBRAM_ERASE_SHIFT   4
#define CSU_CSU_TAMPER_12_BBRAM_ERASE_WIDTH   1
#define CSU_CSU_TAMPER_12_BBRAM_ERASE_MASK    0X00000010

#define CSU_CSU_TAMPER_12_SEC_LOCKDOWN_1_SHIFT   3
#define CSU_CSU_TAMPER_12_SEC_LOCKDOWN_1_WIDTH   1
#define CSU_CSU_TAMPER_12_SEC_LOCKDOWN_1_MASK    0X00000008

#define CSU_CSU_TAMPER_12_SEC_LOCKDOWN_0_SHIFT   2
#define CSU_CSU_TAMPER_12_SEC_LOCKDOWN_0_WIDTH   1
#define CSU_CSU_TAMPER_12_SEC_LOCKDOWN_0_MASK    0X00000004

#define CSU_CSU_TAMPER_12_SYS_RESET_SHIFT   1
#define CSU_CSU_TAMPER_12_SYS_RESET_WIDTH   1
#define CSU_CSU_TAMPER_12_SYS_RESET_MASK    0X00000002

#define CSU_CSU_TAMPER_12_SYS_INTERRUPT_SHIFT   0
#define CSU_CSU_TAMPER_12_SYS_INTERRUPT_WIDTH   1
#define CSU_CSU_TAMPER_12_SYS_INTERRUPT_MASK    0X00000001

/**
 * Register: CSU_CSU_TAMPER_13
 */
#define CSU_CSU_TAMPER_13    ( ( CSU_BASEADDR ) + 0X00005034 )

#define CSU_CSU_TAMPER_13_BBRAM_ERASE_SHIFT   4
#define CSU_CSU_TAMPER_13_BBRAM_ERASE_WIDTH   1
#define CSU_CSU_TAMPER_13_BBRAM_ERASE_MASK    0X00000010

#define CSU_CSU_TAMPER_13_SEC_LOCKDOWN_1_SHIFT   3
#define CSU_CSU_TAMPER_13_SEC_LOCKDOWN_1_WIDTH   1
#define CSU_CSU_TAMPER_13_SEC_LOCKDOWN_1_MASK    0X00000008

#define CSU_CSU_TAMPER_13_SEC_LOCKDOWN_0_SHIFT   2
#define CSU_CSU_TAMPER_13_SEC_LOCKDOWN_0_WIDTH   1
#define CSU_CSU_TAMPER_13_SEC_LOCKDOWN_0_MASK    0X00000004

#define CSU_CSU_TAMPER_13_SYS_RESET_SHIFT   1
#define CSU_CSU_TAMPER_13_SYS_RESET_WIDTH   1
#define CSU_CSU_TAMPER_13_SYS_RESET_MASK    0X00000002

#define CSU_CSU_TAMPER_13_SYS_INTERRUPT_SHIFT   0
#define CSU_CSU_TAMPER_13_SYS_INTERRUPT_WIDTH   1
#define CSU_CSU_TAMPER_13_SYS_INTERRUPT_MASK    0X00000001

/**
 * Register: CSU_CSU_TAMPER_14
 */
#define CSU_CSU_TAMPER_14    ( ( CSU_BASEADDR ) + 0X00005038 )

#define CSU_CSU_TAMPER_14_BBRAM_ERASE_SHIFT   4
#define CSU_CSU_TAMPER_14_BBRAM_ERASE_WIDTH   1
#define CSU_CSU_TAMPER_14_BBRAM_ERASE_MASK    0X00000010

#define CSU_CSU_TAMPER_14_SEC_LOCKDOWN_1_SHIFT   3
#define CSU_CSU_TAMPER_14_SEC_LOCKDOWN_1_WIDTH   1
#define CSU_CSU_TAMPER_14_SEC_LOCKDOWN_1_MASK    0X00000008

#define CSU_CSU_TAMPER_14_SEC_LOCKDOWN_0_SHIFT   2
#define CSU_CSU_TAMPER_14_SEC_LOCKDOWN_0_WIDTH   1
#define CSU_CSU_TAMPER_14_SEC_LOCKDOWN_0_MASK    0X00000004

#define CSU_CSU_TAMPER_14_SYS_RESET_SHIFT   1
#define CSU_CSU_TAMPER_14_SYS_RESET_WIDTH   1
#define CSU_CSU_TAMPER_14_SYS_RESET_MASK    0X00000002

#define CSU_CSU_TAMPER_14_SYS_INTERRUPT_SHIFT   0
#define CSU_CSU_TAMPER_14_SYS_INTERRUPT_WIDTH   1
#define CSU_CSU_TAMPER_14_SYS_INTERRUPT_MASK    0X00000001

/**
 * Register: CSU_CSU_RAM_CFG
 */
#define CSU_CSU_RAM_CFG    ( ( CSU_BASEADDR ) + 0X0000F000 )

#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAA_SHIFT   21
#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAA_WIDTH   3
#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAA_MASK    0X00E00000

#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAB_SHIFT   18
#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAB_WIDTH   3
#define CSU_CSU_RAM_CFG_PCAP_WR_RAM_EMAB_MASK    0X001C0000

#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAA_SHIFT   15
#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAA_WIDTH   3
#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAA_MASK    0X00038000

#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAB_SHIFT   12
#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAB_WIDTH   3
#define CSU_CSU_RAM_CFG_PCAP_RD_RAM_EMAB_MASK    0X00007000

#define CSU_CSU_RAM_CFG_RSA_RAM_EMAS_SHIFT   11
#define CSU_CSU_RAM_CFG_RSA_RAM_EMAS_WIDTH   1
#define CSU_CSU_RAM_CFG_RSA_RAM_EMAS_MASK    0X00000800

#define CSU_CSU_RAM_CFG_RSA_RAM_EMAW_SHIFT   9
#define CSU_CSU_RAM_CFG_RSA_RAM_EMAW_WIDTH   2
#define CSU_CSU_RAM_CFG_RSA_RAM_EMAW_MASK    0X00000600

#define CSU_CSU_RAM_CFG_RSA_RAM_EMA_SHIFT   6
#define CSU_CSU_RAM_CFG_RSA_RAM_EMA_WIDTH   3
#define CSU_CSU_RAM_CFG_RSA_RAM_EMA_MASK    0X000001C0

#define CSU_CSU_RAM_CFG_TMR_RAM_EMAS_SHIFT   5
#define CSU_CSU_RAM_CFG_TMR_RAM_EMAS_WIDTH   1
#define CSU_CSU_RAM_CFG_TMR_RAM_EMAS_MASK    0X00000020

#define CSU_CSU_RAM_CFG_TMR_RAM_EMAW_SHIFT   3
#define CSU_CSU_RAM_CFG_TMR_RAM_EMAW_WIDTH   2
#define CSU_CSU_RAM_CFG_TMR_RAM_EMAW_MASK    0X00000018

#define CSU_CSU_RAM_CFG_TMR_RAM_EMA_SHIFT   0
#define CSU_CSU_RAM_CFG_TMR_RAM_EMA_WIDTH   3
#define CSU_CSU_RAM_CFG_TMR_RAM_EMA_MASK    0X00000007

/**
 * Register: CSU_CSU_ROM_CFG
 */
#define CSU_CSU_ROM_CFG    ( ( CSU_BASEADDR ) + 0X0000F004 )

#define CSU_CSU_ROM_CFG_ROM_A_KEN_SHIFT   31
#define CSU_CSU_ROM_CFG_ROM_A_KEN_WIDTH   1
#define CSU_CSU_ROM_CFG_ROM_A_KEN_MASK    0X80000000

#define CSU_CSU_ROM_CFG_ROM_B_KEN_SHIFT   30
#define CSU_CSU_ROM_CFG_ROM_B_KEN_WIDTH   1
#define CSU_CSU_ROM_CFG_ROM_B_KEN_MASK    0X40000000

#define CSU_CSU_ROM_CFG_ROM_C_KEN_SHIFT   29
#define CSU_CSU_ROM_CFG_ROM_C_KEN_WIDTH   1
#define CSU_CSU_ROM_CFG_ROM_C_KEN_MASK    0X20000000

#define CSU_CSU_ROM_CFG_ROM_D_KEN_SHIFT   28
#define CSU_CSU_ROM_CFG_ROM_D_KEN_WIDTH   1
#define CSU_CSU_ROM_CFG_ROM_D_KEN_MASK    0X10000000

#define CSU_CSU_ROM_CFG_ROM_E_KEN_SHIFT   27
#define CSU_CSU_ROM_CFG_ROM_E_KEN_WIDTH   1
#define CSU_CSU_ROM_CFG_ROM_E_KEN_MASK    0X08000000

#define CSU_CSU_ROM_CFG_ROM_F_KEN_SHIFT   26
#define CSU_CSU_ROM_CFG_ROM_F_KEN_WIDTH   1
#define CSU_CSU_ROM_CFG_ROM_F_KEN_MASK    0X04000000

#define CSU_CSU_ROM_CFG_ROM_G_KEN_SHIFT   25
#define CSU_CSU_ROM_CFG_ROM_G_KEN_WIDTH   1
#define CSU_CSU_ROM_CFG_ROM_G_KEN_MASK    0X02000000

#define CSU_CSU_ROM_CFG_ROM_H_KEN_SHIFT   24
#define CSU_CSU_ROM_CFG_ROM_H_KEN_WIDTH   1
#define CSU_CSU_ROM_CFG_ROM_H_KEN_MASK    0X01000000

#define CSU_CSU_ROM_CFG_ROM_A_EMA_SHIFT   21
#define CSU_CSU_ROM_CFG_ROM_A_EMA_WIDTH   3
#define CSU_CSU_ROM_CFG_ROM_A_EMA_MASK    0X00E00000

#define CSU_CSU_ROM_CFG_ROM_B_EMA_SHIFT   18
#define CSU_CSU_ROM_CFG_ROM_B_EMA_WIDTH   3
#define CSU_CSU_ROM_CFG_ROM_B_EMA_MASK    0X001C0000

#define CSU_CSU_ROM_CFG_ROM_C_EMA_SHIFT   15
#define CSU_CSU_ROM_CFG_ROM_C_EMA_WIDTH   3
#define CSU_CSU_ROM_CFG_ROM_C_EMA_MASK    0X00038000

#define CSU_CSU_ROM_CFG_ROM_D_EMA_SHIFT   12
#define CSU_CSU_ROM_CFG_ROM_D_EMA_WIDTH   3
#define CSU_CSU_ROM_CFG_ROM_D_EMA_MASK    0X00007000

#define CSU_CSU_ROM_CFG_ROM_E_EMA_SHIFT   9
#define CSU_CSU_ROM_CFG_ROM_E_EMA_WIDTH   3
#define CSU_CSU_ROM_CFG_ROM_E_EMA_MASK    0X00000E00

#define CSU_CSU_ROM_CFG_ROM_F_EMA_SHIFT   6
#define CSU_CSU_ROM_CFG_ROM_F_EMA_WIDTH   3
#define CSU_CSU_ROM_CFG_ROM_F_EMA_MASK    0X000001C0

#define CSU_CSU_ROM_CFG_ROM_G_EMA_SHIFT   3
#define CSU_CSU_ROM_CFG_ROM_G_EMA_WIDTH   3
#define CSU_CSU_ROM_CFG_ROM_G_EMA_MASK    0X00000038

#define CSU_CSU_ROM_CFG_ROM_H_EMA_SHIFT   0
#define CSU_CSU_ROM_CFG_ROM_H_EMA_WIDTH   3
#define CSU_CSU_ROM_CFG_ROM_H_EMA_MASK    0X00000007

/**
 * Register: CSU_TEST_CSU_CTRL
 */
#define CSU_TEST_CSU_CTRL    ( ( CSU_BASEADDR ) + 0X0000F008 )

#define CSU_TEST_CSU_CTRL_PSTP_CLK_SEL_SHIFT   0
#define CSU_TEST_CSU_CTRL_PSTP_CLK_SEL_WIDTH   1
#define CSU_TEST_CSU_CTRL_PSTP_CLK_SEL_MASK    0X00000001

/**
 * Register: CSU_CSU_ECO_0
 */
#define CSU_CSU_ECO_0    ( ( CSU_BASEADDR ) + 0X0000FFF4 )

#define CSU_CSU_ECO_0_ECO_SHIFT   0
#define CSU_CSU_ECO_0_ECO_WIDTH   32
#define CSU_CSU_ECO_0_ECO_MASK    0XFFFFFFFF

/**
 * Register: CSU_CSU_ECO_1
 */
#define CSU_CSU_ECO_1    ( ( CSU_BASEADDR ) + 0X0000FFF8 )

#define CSU_CSU_ECO_1_ECO_SHIFT   0
#define CSU_CSU_ECO_1_ECO_WIDTH   32
#define CSU_CSU_ECO_1_ECO_MASK    0XFFFFFFFF

/**
 * Register: CSU_CSU_ECO_2
 */
#define CSU_CSU_ECO_2    ( ( CSU_BASEADDR ) + 0X0000FFFC )

#define CSU_CSU_ECO_2_ECO_SHIFT   0
#define CSU_CSU_ECO_2_ECO_WIDTH   32
#define CSU_CSU_ECO_2_ECO_MASK    0XFFFFFFFF

#ifdef __cplusplus
}
#endif


#endif /* _CSU_H_ */

