#ifndef _FPD_SLCR_H_
#define _FPD_SLCR_H_

#ifdef __cplusplus
extern "C" {
#endif

/**
 * FPD_SLCR Base Address
 */
#define FPD_SLCR_BASEADDR      (FPD_SLCR)

/**
 * Register: FPD_SLCR_WPROT0
 */
#define FPD_SLCR_WPROT0    ( ( FPD_SLCR_BASEADDR ) + 0X00000000 )

#define FPD_SLCR_WPROT0_ACTIVE_SHIFT   0
#define FPD_SLCR_WPROT0_ACTIVE_WIDTH   1
#define FPD_SLCR_WPROT0_ACTIVE_MASK    0X00000001

/**
 * Register: FPD_SLCR_CTRL
 */
#define FPD_SLCR_CTRL    ( ( FPD_SLCR_BASEADDR ) + 0X00000004 )

#define FPD_SLCR_CTRL_SLVERR_ENABLE_SHIFT   0
#define FPD_SLCR_CTRL_SLVERR_ENABLE_WIDTH   1
#define FPD_SLCR_CTRL_SLVERR_ENABLE_MASK    0X00000001

/**
 * Register: FPD_SLCR_ISR
 */
#define FPD_SLCR_ISR    ( ( FPD_SLCR_BASEADDR ) + 0X00000008 )

#define FPD_SLCR_ISR_ADDR_DECODE_ERR_SHIFT   0
#define FPD_SLCR_ISR_ADDR_DECODE_ERR_WIDTH   1
#define FPD_SLCR_ISR_ADDR_DECODE_ERR_MASK    0X00000001

/**
 * Register: FPD_SLCR_IMR
 */
#define FPD_SLCR_IMR    ( ( FPD_SLCR_BASEADDR ) + 0X0000000C )

#define FPD_SLCR_IMR_ADDR_DECODE_ERR_SHIFT   0
#define FPD_SLCR_IMR_ADDR_DECODE_ERR_WIDTH   1
#define FPD_SLCR_IMR_ADDR_DECODE_ERR_MASK    0X00000001

/**
 * Register: FPD_SLCR_IER
 */
#define FPD_SLCR_IER    ( ( FPD_SLCR_BASEADDR ) + 0X00000010 )

#define FPD_SLCR_IER_ADDR_DECODE_ERR_SHIFT   0
#define FPD_SLCR_IER_ADDR_DECODE_ERR_WIDTH   1
#define FPD_SLCR_IER_ADDR_DECODE_ERR_MASK    0X00000001

/**
 * Register: FPD_SLCR_IDR
 */
#define FPD_SLCR_IDR    ( ( FPD_SLCR_BASEADDR ) + 0X00000014 )

#define FPD_SLCR_IDR_ADDR_DECODE_ERR_SHIFT   0
#define FPD_SLCR_IDR_ADDR_DECODE_ERR_WIDTH   1
#define FPD_SLCR_IDR_ADDR_DECODE_ERR_MASK    0X00000001

/**
 * Register: FPD_SLCR_ITR
 */
#define FPD_SLCR_ITR    ( ( FPD_SLCR_BASEADDR ) + 0X00000018 )

#define FPD_SLCR_ITR_ADDR_DECODE_ERR_SHIFT   0
#define FPD_SLCR_ITR_ADDR_DECODE_ERR_WIDTH   1
#define FPD_SLCR_ITR_ADDR_DECODE_ERR_MASK    0X00000001

/**
 * Register: FPD_SLCR_WDT_CLK_SEL
 */
#define FPD_SLCR_WDT_CLK_SEL    ( ( FPD_SLCR_BASEADDR ) + 0X00000100 )

#define FPD_SLCR_WDT_CLK_SEL_SELECT_SHIFT   0
#define FPD_SLCR_WDT_CLK_SEL_SELECT_WIDTH   1
#define FPD_SLCR_WDT_CLK_SEL_SELECT_MASK    0X00000001

/**
 * Register: FPD_SLCR_ECO
 */
#define FPD_SLCR_ECO    ( ( FPD_SLCR_BASEADDR ) + 0X00000FFC )

#define FPD_SLCR_ECO_FIELD_SHIFT   0
#define FPD_SLCR_ECO_FIELD_WIDTH   32
#define FPD_SLCR_ECO_FIELD_MASK    0XFFFFFFFF

#ifdef __cplusplus
}
#endif


#endif /* _FPD_SLCR_H_ */

