#ifndef _CRF_APB_H_
#define _CRF_APB_H_

#ifdef __cplusplus
extern "C" {
#endif

/**
 * CRF_APB Base Address
 */
#define CRF_APB_BASEADDR      ((char *) CRF_APB)

/**
 * Register: CRF_APB_RST_FPD_TOP
 */
#define CRF_APB_RST_FPD_TOP    ( ( CRF_APB_BASEADDR ) + 0X00000100 )

#define CRF_APB_RST_FPD_TOP_PCIE_CFG_RESET_SHIFT   19
#define CRF_APB_RST_FPD_TOP_PCIE_CFG_RESET_WIDTH   1
#define CRF_APB_RST_FPD_TOP_PCIE_CFG_RESET_MASK    0X00080000

#define CRF_APB_RST_FPD_TOP_PCIE_BRIDGE_RESET_SHIFT   18
#define CRF_APB_RST_FPD_TOP_PCIE_BRIDGE_RESET_WIDTH   1
#define CRF_APB_RST_FPD_TOP_PCIE_BRIDGE_RESET_MASK    0X00040000

#define CRF_APB_RST_FPD_TOP_PCIE_CTRL_RESET_SHIFT   17
#define CRF_APB_RST_FPD_TOP_PCIE_CTRL_RESET_WIDTH   1
#define CRF_APB_RST_FPD_TOP_PCIE_CTRL_RESET_MASK    0X00020000

#define CRF_APB_RST_FPD_TOP_DP_RESET_SHIFT   16
#define CRF_APB_RST_FPD_TOP_DP_RESET_WIDTH   1
#define CRF_APB_RST_FPD_TOP_DP_RESET_MASK    0X00010000

#define CRF_APB_RST_FPD_TOP_SWDT_RESET_SHIFT   15
#define CRF_APB_RST_FPD_TOP_SWDT_RESET_WIDTH   1
#define CRF_APB_RST_FPD_TOP_SWDT_RESET_MASK    0X00008000

#define CRF_APB_RST_FPD_TOP_AFI_FM5_RESET_SHIFT   12
#define CRF_APB_RST_FPD_TOP_AFI_FM5_RESET_WIDTH   1
#define CRF_APB_RST_FPD_TOP_AFI_FM5_RESET_MASK    0X00001000

#define CRF_APB_RST_FPD_TOP_AFI_FM4_RESET_SHIFT   11
#define CRF_APB_RST_FPD_TOP_AFI_FM4_RESET_WIDTH   1
#define CRF_APB_RST_FPD_TOP_AFI_FM4_RESET_MASK    0X00000800

#define CRF_APB_RST_FPD_TOP_AFI_FM3_RESET_SHIFT   10
#define CRF_APB_RST_FPD_TOP_AFI_FM3_RESET_WIDTH   1
#define CRF_APB_RST_FPD_TOP_AFI_FM3_RESET_MASK    0X00000400

#define CRF_APB_RST_FPD_TOP_AFI_FM2_RESET_SHIFT   9
#define CRF_APB_RST_FPD_TOP_AFI_FM2_RESET_WIDTH   1
#define CRF_APB_RST_FPD_TOP_AFI_FM2_RESET_MASK    0X00000200

#define CRF_APB_RST_FPD_TOP_AFI_FM1_RESET_SHIFT   8
#define CRF_APB_RST_FPD_TOP_AFI_FM1_RESET_WIDTH   1
#define CRF_APB_RST_FPD_TOP_AFI_FM1_RESET_MASK    0X00000100

#define CRF_APB_RST_FPD_TOP_AFI_FM0_RESET_SHIFT   7
#define CRF_APB_RST_FPD_TOP_AFI_FM0_RESET_WIDTH   1
#define CRF_APB_RST_FPD_TOP_AFI_FM0_RESET_MASK    0X00000080

#define CRF_APB_RST_FPD_TOP_GDMA_RESET_SHIFT   6
#define CRF_APB_RST_FPD_TOP_GDMA_RESET_WIDTH   1
#define CRF_APB_RST_FPD_TOP_GDMA_RESET_MASK    0X00000040

#define CRF_APB_RST_FPD_TOP_GPU_PP1_RESET_SHIFT   5
#define CRF_APB_RST_FPD_TOP_GPU_PP1_RESET_WIDTH   1
#define CRF_APB_RST_FPD_TOP_GPU_PP1_RESET_MASK    0X00000020

#define CRF_APB_RST_FPD_TOP_GPU_PP0_RESET_SHIFT   4
#define CRF_APB_RST_FPD_TOP_GPU_PP0_RESET_WIDTH   1
#define CRF_APB_RST_FPD_TOP_GPU_PP0_RESET_MASK    0X00000010

#define CRF_APB_RST_FPD_TOP_GPU_RESET_SHIFT   3
#define CRF_APB_RST_FPD_TOP_GPU_RESET_WIDTH   1
#define CRF_APB_RST_FPD_TOP_GPU_RESET_MASK    0X00000008

#define CRF_APB_RST_FPD_TOP_GT_RESET_SHIFT   2
#define CRF_APB_RST_FPD_TOP_GT_RESET_WIDTH   1
#define CRF_APB_RST_FPD_TOP_GT_RESET_MASK    0X00000004

#define CRF_APB_RST_FPD_TOP_SATA_RESET_SHIFT   1
#define CRF_APB_RST_FPD_TOP_SATA_RESET_WIDTH   1
#define CRF_APB_RST_FPD_TOP_SATA_RESET_MASK    0X00000002

/**
 * Register: CRF_APB_RST_FPD_APU
 */
#define CRF_APB_RST_FPD_APU    ( ( CRF_APB_BASEADDR ) + 0X00000104 )

#define CRF_APB_RST_FPD_APU_ACPU3_PWRON_RESET_SHIFT   13
#define CRF_APB_RST_FPD_APU_ACPU3_PWRON_RESET_WIDTH   1
#define CRF_APB_RST_FPD_APU_ACPU3_PWRON_RESET_MASK    0X00002000

#define CRF_APB_RST_FPD_APU_ACPU2_PWRON_RESET_SHIFT   12
#define CRF_APB_RST_FPD_APU_ACPU2_PWRON_RESET_WIDTH   1
#define CRF_APB_RST_FPD_APU_ACPU2_PWRON_RESET_MASK    0X00001000

#define CRF_APB_RST_FPD_APU_ACPU1_PWRON_RESET_SHIFT   11
#define CRF_APB_RST_FPD_APU_ACPU1_PWRON_RESET_WIDTH   1
#define CRF_APB_RST_FPD_APU_ACPU1_PWRON_RESET_MASK    0X00000800

#define CRF_APB_RST_FPD_APU_ACPU0_PWRON_RESET_SHIFT   10
#define CRF_APB_RST_FPD_APU_ACPU0_PWRON_RESET_WIDTH   1
#define CRF_APB_RST_FPD_APU_ACPU0_PWRON_RESET_MASK    0X00000400

#define CRF_APB_RST_FPD_APU_APU_L2_RESET_SHIFT   8
#define CRF_APB_RST_FPD_APU_APU_L2_RESET_WIDTH   1
#define CRF_APB_RST_FPD_APU_APU_L2_RESET_MASK    0X00000100

#define CRF_APB_RST_FPD_APU_ACPU3_RESET_SHIFT   3
#define CRF_APB_RST_FPD_APU_ACPU3_RESET_WIDTH   1
#define CRF_APB_RST_FPD_APU_ACPU3_RESET_MASK    0X00000008

#define CRF_APB_RST_FPD_APU_ACPU2_RESET_SHIFT   2
#define CRF_APB_RST_FPD_APU_ACPU2_RESET_WIDTH   1
#define CRF_APB_RST_FPD_APU_ACPU2_RESET_MASK    0X00000004

#define CRF_APB_RST_FPD_APU_ACPU1_RESET_SHIFT   1
#define CRF_APB_RST_FPD_APU_ACPU1_RESET_WIDTH   1
#define CRF_APB_RST_FPD_APU_ACPU1_RESET_MASK    0X00000002

#define CRF_APB_RST_FPD_APU_ACPU0_RESET_SHIFT   0
#define CRF_APB_RST_FPD_APU_ACPU0_RESET_WIDTH   1
#define CRF_APB_RST_FPD_APU_ACPU0_RESET_MASK    0X00000001

/**
 * Register: CRF_APB_RST_DDR_SS
 */
#define CRF_APB_RST_DDR_SS    ( ( CRF_APB_BASEADDR ) + 0X00000108 )

#define CRF_APB_RST_DDR_SS_DDR_RESET_SHIFT   3
#define CRF_APB_RST_DDR_SS_DDR_RESET_WIDTH   1
#define CRF_APB_RST_DDR_SS_DDR_RESET_MASK    0X00000008

#define CRF_APB_RST_DDR_SS_APM_RESET_SHIFT   2
#define CRF_APB_RST_DDR_SS_APM_RESET_WIDTH   1
#define CRF_APB_RST_DDR_SS_APM_RESET_MASK    0X00000004

#ifdef __cplusplus
}
#endif


#endif /* _CRF_APB_H_ */

