/*
 * TBM Register definitions for QSPI Register set for Quad SPI controller
 *
 * Copyright (c) 2016 Xilinx Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#define R_QSPI_CONFIG_REG	0x0
#define   QSPI_CONFIG_REG_LEG_FLSH_WIDTH	1
#define   QSPI_CONFIG_REG_LEG_FLSH_SHIFT	31
#define   QSPI_CONFIG_REG_ENDIAN_WIDTH	1
#define   QSPI_CONFIG_REG_ENDIAN_SHIFT	26
#define   QSPI_CONFIG_REG_HOLDB_DR_WIDTH	1
#define   QSPI_CONFIG_REG_HOLDB_DR_SHIFT	19
#define   QSPI_CONFIG_REG_MAN_START_COM_WIDTH	1
#define   QSPI_CONFIG_REG_MAN_START_COM_SHIFT	16
#define   QSPI_CONFIG_REG_MAN_START_EN_WIDTH	1
#define   QSPI_CONFIG_REG_MAN_START_EN_SHIFT	15
#define   QSPI_CONFIG_REG_MANUAL_CS_WIDTH	1
#define   QSPI_CONFIG_REG_MANUAL_CS_SHIFT	14
#define   QSPI_CONFIG_REG_PCS_WIDTH	1
#define   QSPI_CONFIG_REG_PCS_SHIFT	10
#define   QSPI_CONFIG_REG_REF_CLK_WIDTH	1
#define   QSPI_CONFIG_REG_REF_CLK_SHIFT	8
#define   QSPI_CONFIG_REG_FIFO_WIDTH_WIDTH	2
#define   QSPI_CONFIG_REG_FIFO_WIDTH_SHIFT	6
#define   QSPI_CONFIG_REG_BAUD_RATE_DIV_WIDTH	3
#define   QSPI_CONFIG_REG_BAUD_RATE_DIV_SHIFT	3
#define   QSPI_CONFIG_REG_CLK_PH_WIDTH	1
#define   QSPI_CONFIG_REG_CLK_PH_SHIFT	2
#define   QSPI_CONFIG_REG_CLK_POL_WIDTH	1
#define   QSPI_CONFIG_REG_CLK_POL_SHIFT	1
#define   QSPI_CONFIG_REG_MODE_SEL_WIDTH	1
#define   QSPI_CONFIG_REG_MODE_SEL_SHIFT	0

#define R_QSPI_INTR_STATUS_REG	0x4
#define   QSPI_INTR_STATUS_REG_TXFIFO_EMPTY_WIDTH	1
#define   QSPI_INTR_STATUS_REG_TXFIFO_EMPTY_SHIFT	8
#define   QSPI_INTR_STATUS_REG_TX_FIFO_UNDERFLOW_WIDTH	1
#define   QSPI_INTR_STATUS_REG_TX_FIFO_UNDERFLOW_SHIFT	6
#define   QSPI_INTR_STATUS_REG_RX_FIFO_FULL_WIDTH	1
#define   QSPI_INTR_STATUS_REG_RX_FIFO_FULL_SHIFT	5
#define   QSPI_INTR_STATUS_REG_RX_FIFO_NOT_EMPTY_WIDTH	1
#define   QSPI_INTR_STATUS_REG_RX_FIFO_NOT_EMPTY_SHIFT	4
#define   QSPI_INTR_STATUS_REG_TX_FIFO_FULL_WIDTH	1
#define   QSPI_INTR_STATUS_REG_TX_FIFO_FULL_SHIFT	3
#define   QSPI_INTR_STATUS_REG_TX_FIFO_NOT_FULL_WIDTH	1
#define   QSPI_INTR_STATUS_REG_TX_FIFO_NOT_FULL_SHIFT	2
#define   QSPI_INTR_STATUS_REG_RX_OVERFLOW_WIDTH	1
#define   QSPI_INTR_STATUS_REG_RX_OVERFLOW_SHIFT	0

#define R_QSPI_INTRPT_EN_REG	0x8
#define   QSPI_INTRPT_EN_REG_TXFIFO_EMPTY_WIDTH	1
#define   QSPI_INTRPT_EN_REG_TXFIFO_EMPTY_SHIFT	8
#define   QSPI_INTRPT_EN_REG_TX_FIFO_UNDERFLOW_WIDTH	1
#define   QSPI_INTRPT_EN_REG_TX_FIFO_UNDERFLOW_SHIFT	6
#define   QSPI_INTRPT_EN_REG_RX_FIFO_FULL_WIDTH	1
#define   QSPI_INTRPT_EN_REG_RX_FIFO_FULL_SHIFT	5
#define   QSPI_INTRPT_EN_REG_RX_FIFO_NOT_EMPTY_WIDTH	1
#define   QSPI_INTRPT_EN_REG_RX_FIFO_NOT_EMPTY_SHIFT	4
#define   QSPI_INTRPT_EN_REG_TX_FIFO_FULL_WIDTH	1
#define   QSPI_INTRPT_EN_REG_TX_FIFO_FULL_SHIFT	3
#define   QSPI_INTRPT_EN_REG_TX_FIFO_NOT_FULL_WIDTH	1
#define   QSPI_INTRPT_EN_REG_TX_FIFO_NOT_FULL_SHIFT	2
#define   QSPI_INTRPT_EN_REG_RX_OVERFLOW_WIDTH	1
#define   QSPI_INTRPT_EN_REG_RX_OVERFLOW_SHIFT	0

#define R_QSPI_INTRPT_DIS_REG	0xc
#define   QSPI_INTRPT_DIS_REG_TXFIFO_EMPTY_WIDTH	1
#define   QSPI_INTRPT_DIS_REG_TXFIFO_EMPTY_SHIFT	8
#define   QSPI_INTRPT_DIS_REG_TX_FIFO_UNDERFLOW_WIDTH	1
#define   QSPI_INTRPT_DIS_REG_TX_FIFO_UNDERFLOW_SHIFT	6
#define   QSPI_INTRPT_DIS_REG_RX_FIFO_FULL_WIDTH	1
#define   QSPI_INTRPT_DIS_REG_RX_FIFO_FULL_SHIFT	5
#define   QSPI_INTRPT_DIS_REG_RX_FIFO_NOT_EMPTY_WIDTH	1
#define   QSPI_INTRPT_DIS_REG_RX_FIFO_NOT_EMPTY_SHIFT	4
#define   QSPI_INTRPT_DIS_REG_TX_FIFO_FULL_WIDTH	1
#define   QSPI_INTRPT_DIS_REG_TX_FIFO_FULL_SHIFT	3
#define   QSPI_INTRPT_DIS_REG_TX_FIFO_NOT_FULL_WIDTH	1
#define   QSPI_INTRPT_DIS_REG_TX_FIFO_NOT_FULL_SHIFT	2
#define   QSPI_INTRPT_DIS_REG_RX_OVERFLOW_WIDTH	1
#define   QSPI_INTRPT_DIS_REG_RX_OVERFLOW_SHIFT	0

#define R_QSPI_QSPI_INTRPT_MASK_REG	0x10
#define   QSPI_QSPI_INTRPT_MASK_REG_TXFIFO_EMPTY_WIDTH	1
#define   QSPI_QSPI_INTRPT_MASK_REG_TXFIFO_EMPTY_SHIFT	8
#define   QSPI_QSPI_INTRPT_MASK_REG_TX_FIFO_UNDERFLOW_WIDTH	1
#define   QSPI_QSPI_INTRPT_MASK_REG_TX_FIFO_UNDERFLOW_SHIFT	6
#define   QSPI_QSPI_INTRPT_MASK_REG_RX_FIFO_FULL_WIDTH	1
#define   QSPI_QSPI_INTRPT_MASK_REG_RX_FIFO_FULL_SHIFT	5
#define   QSPI_QSPI_INTRPT_MASK_REG_RX_FIFO_NOT_EMPTY_WIDTH	1
#define   QSPI_QSPI_INTRPT_MASK_REG_RX_FIFO_NOT_EMPTY_SHIFT	4
#define   QSPI_QSPI_INTRPT_MASK_REG_TX_FIFO_FULL_WIDTH	1
#define   QSPI_QSPI_INTRPT_MASK_REG_TX_FIFO_FULL_SHIFT	3
#define   QSPI_QSPI_INTRPT_MASK_REG_TX_FIFO_NOT_FULL_WIDTH	1
#define   QSPI_QSPI_INTRPT_MASK_REG_TX_FIFO_NOT_FULL_SHIFT	2
#define   QSPI_QSPI_INTRPT_MASK_REG_RX_OVERFLOW_WIDTH	1
#define   QSPI_QSPI_INTRPT_MASK_REG_RX_OVERFLOW_SHIFT	0

#define R_QSPI_EN_REG	0x14
#define   QSPI_EN_REG_SPI_EN_WIDTH	1
#define   QSPI_EN_REG_SPI_EN_SHIFT	0

#define R_QSPI_DELAY_REG	0x18
#define   QSPI_DELAY_REG_D_NSS_WIDTH	8
#define   QSPI_DELAY_REG_D_NSS_SHIFT	24
#define   QSPI_DELAY_REG_D_BTWN_WIDTH	8
#define   QSPI_DELAY_REG_D_BTWN_SHIFT	16
#define   QSPI_DELAY_REG_D_AFTER_WIDTH	8
#define   QSPI_DELAY_REG_D_AFTER_SHIFT	8
#define   QSPI_DELAY_REG_D_INT_WIDTH	8
#define   QSPI_DELAY_REG_D_INT_SHIFT	0

#define R_QSPI_TXD0	0x1c
#define   QSPI_TXD0_TXD_WIDTH	32
#define   QSPI_TXD0_TXD_SHIFT	0

#define R_QSPI_RX_DATA_REG	0x20
#define   QSPI_RX_DATA_REG_RX_FIFO_DATA_WIDTH	32
#define   QSPI_RX_DATA_REG_RX_FIFO_DATA_SHIFT	0

#define R_QSPI_SLAVE_IDLE_COUNT_REG	0x24
#define   QSPI_SLAVE_IDLE_COUNT_REG_SLAVE_IDLE_COUNT_WIDTH	8
#define   QSPI_SLAVE_IDLE_COUNT_REG_SLAVE_IDLE_COUNT_SHIFT	0

#define R_QSPI_TX_THRES_REG	0x28
#define   QSPI_TX_THRES_REG_THRESHOLD_OF_TX_FIFO_WIDTH	32
#define   QSPI_TX_THRES_REG_THRESHOLD_OF_TX_FIFO_SHIFT	0

#define R_QSPI_RX_THRES_REG	0x2c
#define   QSPI_RX_THRES_REG_THRESHOLD_OF_RX_FIFO_WIDTH	32
#define   QSPI_RX_THRES_REG_THRESHOLD_OF_RX_FIFO_SHIFT	0

#define R_QSPI_GPIO	0x30
#define   QSPI_GPIO_WP_N_WIDTH	1
#define   QSPI_GPIO_WP_N_SHIFT	0

#define R_QSPI_LPBK_DLY_ADJ	0x38
#define   QSPI_LPBK_DLY_ADJ_USE_LPBK_WIDTH	1
#define   QSPI_LPBK_DLY_ADJ_USE_LPBK_SHIFT	5
#define   QSPI_LPBK_DLY_ADJ_DLY1_WIDTH	2
#define   QSPI_LPBK_DLY_ADJ_DLY1_SHIFT	3
#define   QSPI_LPBK_DLY_ADJ_DLY0_WIDTH	3
#define   QSPI_LPBK_DLY_ADJ_DLY0_SHIFT	0

#define R_QSPI_TXD1	0x80
#define   QSPI_TXD1_TXD_WIDTH	32
#define   QSPI_TXD1_TXD_SHIFT	0

#define R_QSPI_TXD2	0x84
#define   QSPI_TXD2_TXD_WIDTH	32
#define   QSPI_TXD2_TXD_SHIFT	0

#define R_QSPI_TXD3	0x88
#define   QSPI_TXD3_TXD_WIDTH	32
#define   QSPI_TXD3_TXD_SHIFT	0

#define R_QSPI_LQSPI_CFG	0xa0
#define   QSPI_LQSPI_CFG_LQ_MODE_WIDTH	1
#define   QSPI_LQSPI_CFG_LQ_MODE_SHIFT	31
#define   QSPI_LQSPI_CFG_TWO_MEM_WIDTH	1
#define   QSPI_LQSPI_CFG_TWO_MEM_SHIFT	30
#define   QSPI_LQSPI_CFG_SEP_BUS_WIDTH	1
#define   QSPI_LQSPI_CFG_SEP_BUS_SHIFT	29
#define   QSPI_LQSPI_CFG_U_PAGE_WIDTH	1
#define   QSPI_LQSPI_CFG_U_PAGE_SHIFT	28
#define   QSPI_LQSPI_CFG_ADDR_32BIT_WIDTH	1
#define   QSPI_LQSPI_CFG_ADDR_32BIT_SHIFT	27
#define   QSPI_LQSPI_CFG_MODE_EN_WIDTH	1
#define   QSPI_LQSPI_CFG_MODE_EN_SHIFT	25
#define   QSPI_LQSPI_CFG_MODE_ON_WIDTH	1
#define   QSPI_LQSPI_CFG_MODE_ON_SHIFT	24
#define   QSPI_LQSPI_CFG_MODE_BITS_WIDTH	8
#define   QSPI_LQSPI_CFG_MODE_BITS_SHIFT	16
#define   QSPI_LQSPI_CFG_DUMMY_BYTE_WIDTH	3
#define   QSPI_LQSPI_CFG_DUMMY_BYTE_SHIFT	8
#define   QSPI_LQSPI_CFG_INST_CODE_WIDTH	8
#define   QSPI_LQSPI_CFG_INST_CODE_SHIFT	0

#define R_QSPI_LQSPI_STS	0xa4
#define   QSPI_LQSPI_STS_D_FSM_ERR_WIDTH	1
#define   QSPI_LQSPI_STS_D_FSM_ERR_SHIFT	2
#define   QSPI_LQSPI_STS_WR_RECVD_WIDTH	1
#define   QSPI_LQSPI_STS_WR_RECVD_SHIFT	1

#define R_QSPI_CMND_REG	0xc0
#define   QSPI_CMND_REG_RXFIFO_DRAIN_WIDTH	1
#define   QSPI_CMND_REG_RXFIFO_DRAIN_SHIFT	20
#define   QSPI_CMND_REG_RXFIFO_DRAIN_STATUS_WIDTH	1
#define   QSPI_CMND_REG_RXFIFO_DRAIN_STATUS_SHIFT	19
#define   QSPI_CMND_REG_PARTIAL_BYTE_LEN_WIDTH	3
#define   QSPI_CMND_REG_PARTIAL_BYTE_LEN_SHIFT	16
#define   QSPI_CMND_REG_EXT_ADD_WIDTH	1
#define   QSPI_CMND_REG_EXT_ADD_SHIFT	15
#define   QSPI_CMND_REG_RX_DISCARD_REG_WIDTH	7
#define   QSPI_CMND_REG_RX_DISCARD_REG_SHIFT	8
#define   QSPI_CMND_REG_DUMMY_CYCLES_WIDTH	6
#define   QSPI_CMND_REG_DUMMY_CYCLES_SHIFT	2
#define   QSPI_CMND_REG_DMA_EN_WIDTH	1
#define   QSPI_CMND_REG_DMA_EN_SHIFT	1
#define   QSPI_CMND_REG_PUSH_WAIT_WIDTH	1
#define   QSPI_CMND_REG_PUSH_WAIT_SHIFT	0

#define R_QSPI_TRANSFER_SIZE	0xc4
#define   QSPI_TRANSFER_SIZE_SIZE_WIDTH	27
#define   QSPI_TRANSFER_SIZE_SIZE_SHIFT	2

#define R_QSPI_DUMMY_CYCLE_EN	0xc8
#define   QSPI_DUMMY_CYCLE_EN_DUMMY_CYCLE_EN_WIDTH	1
#define   QSPI_DUMMY_CYCLE_EN_DUMMY_CYCLE_EN_SHIFT	0

#define R_QSPI_MOD_ID	0xfc
#define   QSPI_MOD_ID___WIDTH	32
#define   QSPI_MOD_ID___SHIFT	0

#define R_QSPI_GQSPI_CFG	0x100
#define   QSPI_GQSPI_CFG_MODE_EN_WIDTH	2
#define   QSPI_GQSPI_CFG_MODE_EN_SHIFT	30
#define   QSPI_GQSPI_CFG_GEN_FIFO_START_MODE_WIDTH	1
#define   QSPI_GQSPI_CFG_GEN_FIFO_START_MODE_SHIFT	29
#define   QSPI_GQSPI_CFG_START_GEN_FIFO_WIDTH	1
#define   QSPI_GQSPI_CFG_START_GEN_FIFO_SHIFT	28
#define   QSPI_GQSPI_CFG_ENDIAN_WIDTH	1
#define   QSPI_GQSPI_CFG_ENDIAN_SHIFT	26
#define   QSPI_GQSPI_CFG_EN_POLL_TIMEOUT_WIDTH	1
#define   QSPI_GQSPI_CFG_EN_POLL_TIMEOUT_SHIFT	20
#define   QSPI_GQSPI_CFG_WP_HOLD_WIDTH	1
#define   QSPI_GQSPI_CFG_WP_HOLD_SHIFT	19
#define   QSPI_GQSPI_CFG_BAUD_RATE_DIV_WIDTH	3
#define   QSPI_GQSPI_CFG_BAUD_RATE_DIV_SHIFT	3
#define   QSPI_GQSPI_CFG_CLK_PH_WIDTH	1
#define   QSPI_GQSPI_CFG_CLK_PH_SHIFT	2
#define   QSPI_GQSPI_CFG_CLK_POL_WIDTH	1
#define   QSPI_GQSPI_CFG_CLK_POL_SHIFT	1

#define R_QSPI_GQSPI_ISR	0x104
#define   QSPI_GQSPI_ISR_RX_FIFO_EMPTY_WIDTH	1
#define   QSPI_GQSPI_ISR_RX_FIFO_EMPTY_SHIFT	11
#define   QSPI_GQSPI_ISR_GEN_FIFO_FULL_WIDTH	1
#define   QSPI_GQSPI_ISR_GEN_FIFO_FULL_SHIFT	10
#define   QSPI_GQSPI_ISR_GEN_FIFO_NOT_FULL_WIDTH	1
#define   QSPI_GQSPI_ISR_GEN_FIFO_NOT_FULL_SHIFT	9
#define   QSPI_GQSPI_ISR_TX_FIFO_EMPTY_WIDTH	1
#define   QSPI_GQSPI_ISR_TX_FIFO_EMPTY_SHIFT	8
#define   QSPI_GQSPI_ISR_GEN_FIFO_EMPTY_WIDTH	1
#define   QSPI_GQSPI_ISR_GEN_FIFO_EMPTY_SHIFT	7
#define   QSPI_GQSPI_ISR_RX_FIFO_FULL_WIDTH	1
#define   QSPI_GQSPI_ISR_RX_FIFO_FULL_SHIFT	5
#define   QSPI_GQSPI_ISR_RX_FIFO_NOT_EMPTY_WIDTH	1
#define   QSPI_GQSPI_ISR_RX_FIFO_NOT_EMPTY_SHIFT	4
#define   QSPI_GQSPI_ISR_TX_FIFO_FULL_WIDTH	1
#define   QSPI_GQSPI_ISR_TX_FIFO_FULL_SHIFT	3
#define   QSPI_GQSPI_ISR_TX_FIFO_NOT_FULL_WIDTH	1
#define   QSPI_GQSPI_ISR_TX_FIFO_NOT_FULL_SHIFT	2
#define   QSPI_GQSPI_ISR_POLL_TIME_EXPIRE_WIDTH	1
#define   QSPI_GQSPI_ISR_POLL_TIME_EXPIRE_SHIFT	1

#define R_QSPI_GQSPI_IER	0x108
#define   QSPI_GQSPI_IER_RX_FIFO_EMPTY_WIDTH	1
#define   QSPI_GQSPI_IER_RX_FIFO_EMPTY_SHIFT	11
#define   QSPI_GQSPI_IER_GEN_FIFO_FULL_WIDTH	1
#define   QSPI_GQSPI_IER_GEN_FIFO_FULL_SHIFT	10
#define   QSPI_GQSPI_IER_GEN_FIFO_NOT_FULL_WIDTH	1
#define   QSPI_GQSPI_IER_GEN_FIFO_NOT_FULL_SHIFT	9
#define   QSPI_GQSPI_IER_TX_FIFO_EMPTY_WIDTH	1
#define   QSPI_GQSPI_IER_TX_FIFO_EMPTY_SHIFT	8
#define   QSPI_GQSPI_IER_GEN_FIFO_EMPTY_WIDTH	1
#define   QSPI_GQSPI_IER_GEN_FIFO_EMPTY_SHIFT	7
#define   QSPI_GQSPI_IER_RX_FIFO_FULL_WIDTH	1
#define   QSPI_GQSPI_IER_RX_FIFO_FULL_SHIFT	5
#define   QSPI_GQSPI_IER_RX_FIFO_NOT_EMPTY_WIDTH	1
#define   QSPI_GQSPI_IER_RX_FIFO_NOT_EMPTY_SHIFT	4
#define   QSPI_GQSPI_IER_TX_FIFO_FULL_WIDTH	1
#define   QSPI_GQSPI_IER_TX_FIFO_FULL_SHIFT	3
#define   QSPI_GQSPI_IER_TX_FIFO_NOT_FULL_WIDTH	1
#define   QSPI_GQSPI_IER_TX_FIFO_NOT_FULL_SHIFT	2
#define   QSPI_GQSPI_IER_POLL_TIME_EXPIRE_WIDTH	1
#define   QSPI_GQSPI_IER_POLL_TIME_EXPIRE_SHIFT	1

#define R_QSPI_GQSPI_IDR	0x10c
#define   QSPI_GQSPI_IDR_RX_FIFO_EMPTY_WIDTH	1
#define   QSPI_GQSPI_IDR_RX_FIFO_EMPTY_SHIFT	11
#define   QSPI_GQSPI_IDR_GEN_FIFO_FULL_WIDTH	1
#define   QSPI_GQSPI_IDR_GEN_FIFO_FULL_SHIFT	10
#define   QSPI_GQSPI_IDR_GEN_FIFO_NOT_FULL_WIDTH	1
#define   QSPI_GQSPI_IDR_GEN_FIFO_NOT_FULL_SHIFT	9
#define   QSPI_GQSPI_IDR_TX_FIFO_EMPTY_WIDTH	1
#define   QSPI_GQSPI_IDR_TX_FIFO_EMPTY_SHIFT	8
#define   QSPI_GQSPI_IDR_GEN_FIFO_EMPTY_WIDTH	1
#define   QSPI_GQSPI_IDR_GEN_FIFO_EMPTY_SHIFT	7
#define   QSPI_GQSPI_IDR_RX_FIFO_FULL_WIDTH	1
#define   QSPI_GQSPI_IDR_RX_FIFO_FULL_SHIFT	5
#define   QSPI_GQSPI_IDR_RX_FIFO_NOT_EMPTY_WIDTH	1
#define   QSPI_GQSPI_IDR_RX_FIFO_NOT_EMPTY_SHIFT	4
#define   QSPI_GQSPI_IDR_TX_FIFO_FULL_WIDTH	1
#define   QSPI_GQSPI_IDR_TX_FIFO_FULL_SHIFT	3
#define   QSPI_GQSPI_IDR_TX_FIFO_NOT_FULL_WIDTH	1
#define   QSPI_GQSPI_IDR_TX_FIFO_NOT_FULL_SHIFT	2
#define   QSPI_GQSPI_IDR_POLL_TIME_EXPIRE_WIDTH	1
#define   QSPI_GQSPI_IDR_POLL_TIME_EXPIRE_SHIFT	1

#define R_QSPI_GQSPI_IMASK	0x110
#define   QSPI_GQSPI_IMASK_RX_FIFO_EMPTY_WIDTH	1
#define   QSPI_GQSPI_IMASK_RX_FIFO_EMPTY_SHIFT	11
#define   QSPI_GQSPI_IMASK_GEN_FIFO_FULL_WIDTH	1
#define   QSPI_GQSPI_IMASK_GEN_FIFO_FULL_SHIFT	10
#define   QSPI_GQSPI_IMASK_GEN_FIFO_NOT_FULL_WIDTH	1
#define   QSPI_GQSPI_IMASK_GEN_FIFO_NOT_FULL_SHIFT	9
#define   QSPI_GQSPI_IMASK_TX_FIFO_EMPTY_WIDTH	1
#define   QSPI_GQSPI_IMASK_TX_FIFO_EMPTY_SHIFT	8
#define   QSPI_GQSPI_IMASK_GEN_FIFO_EMPTY_WIDTH	1
#define   QSPI_GQSPI_IMASK_GEN_FIFO_EMPTY_SHIFT	7
#define   QSPI_GQSPI_IMASK_RX_FIFO_FULL_WIDTH	1
#define   QSPI_GQSPI_IMASK_RX_FIFO_FULL_SHIFT	5
#define   QSPI_GQSPI_IMASK_RX_FIFO_NOT_EMPTY_WIDTH	1
#define   QSPI_GQSPI_IMASK_RX_FIFO_NOT_EMPTY_SHIFT	4
#define   QSPI_GQSPI_IMASK_TX_FIFO_FULL_WIDTH	1
#define   QSPI_GQSPI_IMASK_TX_FIFO_FULL_SHIFT	3
#define   QSPI_GQSPI_IMASK_TX_FIFO_NOT_FULL_WIDTH	1
#define   QSPI_GQSPI_IMASK_TX_FIFO_NOT_FULL_SHIFT	2
#define   QSPI_GQSPI_IMASK_POLL_TIME_EXPIRE_WIDTH	1
#define   QSPI_GQSPI_IMASK_POLL_TIME_EXPIRE_SHIFT	1

#define R_QSPI_GQSPI_EN_REG	0x114
#define   QSPI_GQSPI_EN_REG_GQSPI_EN_WIDTH	1
#define   QSPI_GQSPI_EN_REG_GQSPI_EN_SHIFT	0

#define R_QSPI_GQSPI_TXD	0x11c
#define   QSPI_GQSPI_TXD_TX_DATA_WIDTH	32
#define   QSPI_GQSPI_TXD_TX_DATA_SHIFT	0

#define R_QSPI_GQSPI_RXD	0x120
#define   QSPI_GQSPI_RXD_RX_DATA_WIDTH	32
#define   QSPI_GQSPI_RXD_RX_DATA_SHIFT	0

#define R_QSPI_GQSPI_TX_THRESH	0x128
#define   QSPI_GQSPI_TX_THRESH_LEVEL_TX_FIFO_WIDTH	6
#define   QSPI_GQSPI_TX_THRESH_LEVEL_TX_FIFO_SHIFT	0

#define R_QSPI_GQSPI_RX_THRESH	0x12c
#define   QSPI_GQSPI_RX_THRESH_LEVEL_RX_FIFO_WIDTH	6
#define   QSPI_GQSPI_RX_THRESH_LEVEL_RX_FIFO_SHIFT	0

#define R_QSPI_GQSPI_GPIO	0x130
#define   QSPI_GQSPI_GPIO_WP_N_WIDTH	1
#define   QSPI_GQSPI_GPIO_WP_N_SHIFT	0

#define R_QSPI_GQSPI_LPBK_DLY_ADJ	0x138
#define   QSPI_GQSPI_LPBK_DLY_ADJ_USE_LPBK_WIDTH	1
#define   QSPI_GQSPI_LPBK_DLY_ADJ_USE_LPBK_SHIFT	5
#define   QSPI_GQSPI_LPBK_DLY_ADJ_DLY1_WIDTH	2
#define   QSPI_GQSPI_LPBK_DLY_ADJ_DLY1_SHIFT	3
#define   QSPI_GQSPI_LPBK_DLY_ADJ_DLY0_WIDTH	3
#define   QSPI_GQSPI_LPBK_DLY_ADJ_DLY0_SHIFT	0

#define R_QSPI_GQSPI_GEN_FIFO	0x140
#define   QSPI_GQSPI_GEN_FIFO_GEN_DATA_WIDTH	20
#define   QSPI_GQSPI_GEN_FIFO_GEN_DATA_SHIFT	0

#define R_QSPI_GQSPI_SEL	0x144
#define   QSPI_GQSPI_SEL_GENERIC_QSPI_SEL_WIDTH	1
#define   QSPI_GQSPI_SEL_GENERIC_QSPI_SEL_SHIFT	0

#define R_QSPI_GQSPI_FIFO_CTRL	0x14c
#define   QSPI_GQSPI_FIFO_CTRL_RST_RX_FIFO_WIDTH	1
#define   QSPI_GQSPI_FIFO_CTRL_RST_RX_FIFO_SHIFT	2
#define   QSPI_GQSPI_FIFO_CTRL_RST_TX_FIFO_WIDTH	1
#define   QSPI_GQSPI_FIFO_CTRL_RST_TX_FIFO_SHIFT	1
#define   QSPI_GQSPI_FIFO_CTRL_RST_GEN_FIFO_WIDTH	1
#define   QSPI_GQSPI_FIFO_CTRL_RST_GEN_FIFO_SHIFT	0

#define R_QSPI_GQSPI_GF_THRESH	0x150
#define   QSPI_GQSPI_GF_THRESH_LEVEL_GF_FIFO_WIDTH	5
#define   QSPI_GQSPI_GF_THRESH_LEVEL_GF_FIFO_SHIFT	0

#define R_QSPI_GQSPI_POLL_CFG	0x154
#define   QSPI_GQSPI_POLL_CFG_EN_MASK_UPPER_WIDTH	1
#define   QSPI_GQSPI_POLL_CFG_EN_MASK_UPPER_SHIFT	31
#define   QSPI_GQSPI_POLL_CFG_EN_MASK_LOWER_WIDTH	1
#define   QSPI_GQSPI_POLL_CFG_EN_MASK_LOWER_SHIFT	30
#define   QSPI_GQSPI_POLL_CFG_MASK_EN_WIDTH	8
#define   QSPI_GQSPI_POLL_CFG_MASK_EN_SHIFT	8
#define   QSPI_GQSPI_POLL_CFG_DATA_VALUE_WIDTH	8
#define   QSPI_GQSPI_POLL_CFG_DATA_VALUE_SHIFT	0

#define R_QSPI_GQSPI_P_TIMEOUT	0x158
#define   QSPI_GQSPI_P_TIMEOUT_VALUE_WIDTH	32
#define   QSPI_GQSPI_P_TIMEOUT_VALUE_SHIFT	0

#define R_QSPI_GQSPI_XFER_STS	0x15c
#define   QSPI_GQSPI_XFER_STS_PEND_BYTES_WIDTH	32
#define   QSPI_GQSPI_XFER_STS_PEND_BYTES_SHIFT	0

#define R_QSPI_GQSPI_GF_SNAPSHOT	0x160
#define   QSPI_GQSPI_GF_SNAPSHOT_SNAP_SHOT_WIDTH	20
#define   QSPI_GQSPI_GF_SNAPSHOT_SNAP_SHOT_SHIFT	0

#define R_QSPI_GQSPI_RX_COPY	0x164
#define   QSPI_GQSPI_RX_COPY_UPPER_RX_DATA_WIDTH	8
#define   QSPI_GQSPI_RX_COPY_UPPER_RX_DATA_SHIFT	8
#define   QSPI_GQSPI_RX_COPY_LOWER_RX_DATA_WIDTH	8
#define   QSPI_GQSPI_RX_COPY_LOWER_RX_DATA_SHIFT	0

#define R_QSPI_QSPI_DATA_DLY_ADJ	0x1f8
#define   QSPI_QSPI_DATA_DLY_ADJ_USE_DATA_DLY_WIDTH	1
#define   QSPI_QSPI_DATA_DLY_ADJ_USE_DATA_DLY_SHIFT	31
#define   QSPI_QSPI_DATA_DLY_ADJ_DATA_DLY_ADJ_WIDTH	3
#define   QSPI_QSPI_DATA_DLY_ADJ_DATA_DLY_ADJ_SHIFT	28

#define R_QSPI_GQSPI_MOD_ID	0x1fc
#define   QSPI_GQSPI_MOD_ID_MOD_ID_WIDTH	32
#define   QSPI_GQSPI_MOD_ID_MOD_ID_SHIFT	0

#define R_QSPI_QSPIDMA_DST_ADDR	0x800
#define   QSPI_QSPIDMA_DST_ADDR_ADDR_WIDTH	30
#define   QSPI_QSPIDMA_DST_ADDR_ADDR_SHIFT	2

#define R_QSPI_QSPIDMA_DST_SIZE	0x804
#define   QSPI_QSPIDMA_DST_SIZE_SIZE_WIDTH	27
#define   QSPI_QSPIDMA_DST_SIZE_SIZE_SHIFT	2

#define R_QSPI_QSPIDMA_DST_STS	0x808
#define   QSPI_QSPIDMA_DST_STS_DONE_CNT_WIDTH	3
#define   QSPI_QSPIDMA_DST_STS_DONE_CNT_SHIFT	13
#define   QSPI_QSPIDMA_DST_STS_DST_FIFO_LEVEL_WIDTH	8
#define   QSPI_QSPIDMA_DST_STS_DST_FIFO_LEVEL_SHIFT	5
#define   QSPI_QSPIDMA_DST_STS_WR_OUTSTANDING_WIDTH	4
#define   QSPI_QSPIDMA_DST_STS_WR_OUTSTANDING_SHIFT	1
#define   QSPI_QSPIDMA_DST_STS_BUSY_WIDTH	1
#define   QSPI_QSPIDMA_DST_STS_BUSY_SHIFT	0

#define R_QSPI_QSPIDMA_DST_CTRL	0x80c
#define   QSPI_QSPIDMA_DST_CTRL_FIFO_LVL_HIT_THRESH_WIDTH	7
#define   QSPI_QSPIDMA_DST_CTRL_FIFO_LVL_HIT_THRESH_SHIFT	25
#define   QSPI_QSPIDMA_DST_CTRL_APB_ERR_RESP_WIDTH	1
#define   QSPI_QSPIDMA_DST_CTRL_APB_ERR_RESP_SHIFT	24
#define   QSPI_QSPIDMA_DST_CTRL_ENDIANNESS_WIDTH	1
#define   QSPI_QSPIDMA_DST_CTRL_ENDIANNESS_SHIFT	23
#define   QSPI_QSPIDMA_DST_CTRL_AXI_BRST_TYPE_WIDTH	1
#define   QSPI_QSPIDMA_DST_CTRL_AXI_BRST_TYPE_SHIFT	22
#define   QSPI_QSPIDMA_DST_CTRL_TIMEOUT_VAL_WIDTH	12
#define   QSPI_QSPIDMA_DST_CTRL_TIMEOUT_VAL_SHIFT	10
#define   QSPI_QSPIDMA_DST_CTRL_FIFO_THRESH_WIDTH	8
#define   QSPI_QSPIDMA_DST_CTRL_FIFO_THRESH_SHIFT	2
#define   QSPI_QSPIDMA_DST_CTRL_PAUSE_STRM_WIDTH	1
#define   QSPI_QSPIDMA_DST_CTRL_PAUSE_STRM_SHIFT	1
#define   QSPI_QSPIDMA_DST_CTRL_PAUSE_MEM_WIDTH	1
#define   QSPI_QSPIDMA_DST_CTRL_PAUSE_MEM_SHIFT	0

#define R_QSPI_QSPIDMA_DST_I_STS	0x814
#define   QSPI_QSPIDMA_DST_I_STS_FIFO_OVERFLOW_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_STS_FIFO_OVERFLOW_SHIFT	7
#define   QSPI_QSPIDMA_DST_I_STS_INVALID_APB_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_STS_INVALID_APB_SHIFT	6
#define   QSPI_QSPIDMA_DST_I_STS_THRESH_HIT_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_STS_THRESH_HIT_SHIFT	5
#define   QSPI_QSPIDMA_DST_I_STS_TIMEOUT_MEM_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_STS_TIMEOUT_MEM_SHIFT	4
#define   QSPI_QSPIDMA_DST_I_STS_TIMEOUT_STRM_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_STS_TIMEOUT_STRM_SHIFT	3
#define   QSPI_QSPIDMA_DST_I_STS_AXI_BRESP_ERR_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_STS_AXI_BRESP_ERR_SHIFT	2
#define   QSPI_QSPIDMA_DST_I_STS_DONE_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_STS_DONE_SHIFT	1

#define R_QSPI_QSPIDMA_DST_I_EN	0x818
#define   QSPI_QSPIDMA_DST_I_EN_FIFO_OVERFLOW_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_EN_FIFO_OVERFLOW_SHIFT	7
#define   QSPI_QSPIDMA_DST_I_EN_INVALID_APB_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_EN_INVALID_APB_SHIFT	6
#define   QSPI_QSPIDMA_DST_I_EN_THRESH_HIT_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_EN_THRESH_HIT_SHIFT	5
#define   QSPI_QSPIDMA_DST_I_EN_TIMEOUT_MEM_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_EN_TIMEOUT_MEM_SHIFT	4
#define   QSPI_QSPIDMA_DST_I_EN_TIMEOUT_STRM_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_EN_TIMEOUT_STRM_SHIFT	3
#define   QSPI_QSPIDMA_DST_I_EN_AXI_BRESP_ERR_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_EN_AXI_BRESP_ERR_SHIFT	2
#define   QSPI_QSPIDMA_DST_I_EN_DONE_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_EN_DONE_SHIFT	1

#define R_QSPI_QSPIDMA_DST_I_DIS	0x81c
#define   QSPI_QSPIDMA_DST_I_DIS_FIFO_OVERFLOW_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_DIS_FIFO_OVERFLOW_SHIFT	7
#define   QSPI_QSPIDMA_DST_I_DIS_INVALID_APB_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_DIS_INVALID_APB_SHIFT	6
#define   QSPI_QSPIDMA_DST_I_DIS_THRESH_HIT_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_DIS_THRESH_HIT_SHIFT	5
#define   QSPI_QSPIDMA_DST_I_DIS_TIMEOUT_MEM_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_DIS_TIMEOUT_MEM_SHIFT	4
#define   QSPI_QSPIDMA_DST_I_DIS_TIMEOUT_STRM_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_DIS_TIMEOUT_STRM_SHIFT	3
#define   QSPI_QSPIDMA_DST_I_DIS_AXI_BRESP_ERR_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_DIS_AXI_BRESP_ERR_SHIFT	2
#define   QSPI_QSPIDMA_DST_I_DIS_DONE_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_DIS_DONE_SHIFT	1

#define R_QSPI_QSPIDMA_DST_I_MASK	0x820
#define   QSPI_QSPIDMA_DST_I_MASK_FIFO_OVERFLOW_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_MASK_FIFO_OVERFLOW_SHIFT	7
#define   QSPI_QSPIDMA_DST_I_MASK_INVALID_APB_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_MASK_INVALID_APB_SHIFT	6
#define   QSPI_QSPIDMA_DST_I_MASK_THRESH_HIT_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_MASK_THRESH_HIT_SHIFT	5
#define   QSPI_QSPIDMA_DST_I_MASK_TIMEOUT_MEM_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_MASK_TIMEOUT_MEM_SHIFT	4
#define   QSPI_QSPIDMA_DST_I_MASK_TIMEOUT_STRM_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_MASK_TIMEOUT_STRM_SHIFT	3
#define   QSPI_QSPIDMA_DST_I_MASK_AXI_BRESP_ERR_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_MASK_AXI_BRESP_ERR_SHIFT	2
#define   QSPI_QSPIDMA_DST_I_MASK_DONE_WIDTH	1
#define   QSPI_QSPIDMA_DST_I_MASK_DONE_SHIFT	1

#define R_QSPI_QSPIDMA_DST_CTRL2	0x824
#define   QSPI_QSPIDMA_DST_CTRL2_RAM_EMASA_WIDTH	1
#define   QSPI_QSPIDMA_DST_CTRL2_RAM_EMASA_SHIFT	27
#define   QSPI_QSPIDMA_DST_CTRL2_AWCACHE_WIDTH	3
#define   QSPI_QSPIDMA_DST_CTRL2_AWCACHE_SHIFT	24
#define   QSPI_QSPIDMA_DST_CTRL2_TIMEOUT_EN_WIDTH	1
#define   QSPI_QSPIDMA_DST_CTRL2_TIMEOUT_EN_SHIFT	22
#define   QSPI_QSPIDMA_DST_CTRL2_RAM_EMAB_WIDTH	3
#define   QSPI_QSPIDMA_DST_CTRL2_RAM_EMAB_SHIFT	19
#define   QSPI_QSPIDMA_DST_CTRL2_RAM_EMAA_WIDTH	3
#define   QSPI_QSPIDMA_DST_CTRL2_RAM_EMAA_SHIFT	16
#define   QSPI_QSPIDMA_DST_CTRL2_TIMEOUT_PRE_WIDTH	12
#define   QSPI_QSPIDMA_DST_CTRL2_TIMEOUT_PRE_SHIFT	4
#define   QSPI_QSPIDMA_DST_CTRL2_MAX_OUTS_CMDS_WIDTH	4
#define   QSPI_QSPIDMA_DST_CTRL2_MAX_OUTS_CMDS_SHIFT	0

#define R_QSPI_QSPIDMA_DST_ADDR_MSB	0x828
#define   QSPI_QSPIDMA_DST_ADDR_MSB_ADDR_MSB_WIDTH	12
#define   QSPI_QSPIDMA_DST_ADDR_MSB_ADDR_MSB_SHIFT	0

#define R_QSPI_QSPIDMA_FUTURE_ECO	0xffc
#define   QSPI_QSPIDMA_FUTURE_ECO_VAL_WIDTH	32
#define   QSPI_QSPIDMA_FUTURE_ECO_VAL_SHIFT	0

