#ifndef _CRL_APB_H_
#define _CRL_APB_H_

#ifdef __cplusplus
extern "C" {
#endif

/**
 * CRL_APB Base Address
 */
#define CRL_APB_BASEADDR      CRL_APB

/**
 * Register: CRL_APB_BOOT_MODE_USER
 */
#define CRL_APB_BOOT_MODE_USER    ( ( CRL_APB_BASEADDR ) + 0X00000200 )

#define CRL_APB_BOOT_MODE_USER_ALT_BOOT_MODE_SHIFT   12
#define CRL_APB_BOOT_MODE_USER_ALT_BOOT_MODE_WIDTH   4
#define CRL_APB_BOOT_MODE_USER_ALT_BOOT_MODE_MASK    0X0000F000

#define CRL_APB_BOOT_MODE_USER_USE_ALT_SHIFT   8
#define CRL_APB_BOOT_MODE_USER_USE_ALT_WIDTH   1
#define CRL_APB_BOOT_MODE_USER_USE_ALT_MASK    0X00000100

#define CRL_APB_BOOT_MODE_USER_BOOT_MODE_SHIFT   0
#define CRL_APB_BOOT_MODE_USER_BOOT_MODE_WIDTH   4
#define CRL_APB_BOOT_MODE_USER_BOOT_MODE_MASK    0X0000000F

/**
 * Register: CRL_APB_BOOT_MODE_POR
 */
#define CRL_APB_BOOT_MODE_POR    ( ( CRL_APB_BASEADDR ) + 0X00000204 )

#define CRL_APB_BOOT_MODE_POR_BOOT_MODE2_SHIFT   8
#define CRL_APB_BOOT_MODE_POR_BOOT_MODE2_WIDTH   4
#define CRL_APB_BOOT_MODE_POR_BOOT_MODE2_MASK    0X00000F00

#define CRL_APB_BOOT_MODE_POR_BOOT_MODE1_SHIFT   4
#define CRL_APB_BOOT_MODE_POR_BOOT_MODE1_WIDTH   4
#define CRL_APB_BOOT_MODE_POR_BOOT_MODE1_MASK    0X000000F0

#define CRL_APB_BOOT_MODE_POR_BOOT_MODE0_SHIFT   0
#define CRL_APB_BOOT_MODE_POR_BOOT_MODE0_WIDTH   4
#define CRL_APB_BOOT_MODE_POR_BOOT_MODE0_MASK    0X0000000F

/**
 * Register: CRL_APB_MIMIC_RST
 */
#define CRL_APB_MIMIC_RST    ( ( CRL_APB_BASEADDR ) + 0X00000214 )

#define CRL_APB_MIMIC_RST_PSONLY_SHIFT   5
#define CRL_APB_MIMIC_RST_PSONLY_WIDTH   1
#define CRL_APB_MIMIC_RST_PSONLY_MASK    0X00000020

#define CRL_APB_MIMIC_RST_DEBUG_ONLY_SHIFT   4
#define CRL_APB_MIMIC_RST_DEBUG_ONLY_WIDTH   1
#define CRL_APB_MIMIC_RST_DEBUG_ONLY_MASK    0X00000010

#define CRL_APB_MIMIC_RST_DEBUG_SYS_SHIFT   3
#define CRL_APB_MIMIC_RST_DEBUG_SYS_WIDTH   1
#define CRL_APB_MIMIC_RST_DEBUG_SYS_MASK    0X00000008

#define CRL_APB_MIMIC_RST_SOFT_SHIFT   2
#define CRL_APB_MIMIC_RST_SOFT_WIDTH   1
#define CRL_APB_MIMIC_RST_SOFT_MASK    0X00000004

#define CRL_APB_MIMIC_RST_SRST_SHIFT   1
#define CRL_APB_MIMIC_RST_SRST_WIDTH   1
#define CRL_APB_MIMIC_RST_SRST_MASK    0X00000002

#define CRL_APB_MIMIC_RST_PMU_SYS_SHIFT   0
#define CRL_APB_MIMIC_RST_PMU_SYS_WIDTH   1
#define CRL_APB_MIMIC_RST_PMU_SYS_MASK    0X00000001

/**
 * Register: CRL_APB_RESET_CTRL
 */
#define CRL_APB_RESET_CTRL    ( ( CRL_APB_BASEADDR ) + 0X00000218 )

#define CRL_APB_RESET_CTRL_SOFT_RESET_SHIFT   4
#define CRL_APB_RESET_CTRL_SOFT_RESET_WIDTH   1
#define CRL_APB_RESET_CTRL_SOFT_RESET_MASK    0X00000010

#define CRL_APB_RESET_CTRL_PSONLY_RELEASE_SHIFT   1
#define CRL_APB_RESET_CTRL_PSONLY_RELEASE_WIDTH   1
#define CRL_APB_RESET_CTRL_PSONLY_RELEASE_MASK    0X00000002

#define CRL_APB_RESET_CTRL_SRST_DIS_SHIFT   0
#define CRL_APB_RESET_CTRL_SRST_DIS_WIDTH   1
#define CRL_APB_RESET_CTRL_SRST_DIS_MASK    0X00000001

/**
 * Register: CRL_APB_BLOCKONLY_RST
 */
#define CRL_APB_BLOCKONLY_RST    ( ( CRL_APB_BASEADDR ) + 0X0000021C )

#define CRL_APB_BLOCKONLY_RST_MIMIC_SHIFT   3
#define CRL_APB_BLOCKONLY_RST_MIMIC_WIDTH   1
#define CRL_APB_BLOCKONLY_RST_MIMIC_MASK    0X00000008

#define CRL_APB_BLOCKONLY_RST_DEBUG_ONLY_SHIFT   0
#define CRL_APB_BLOCKONLY_RST_DEBUG_ONLY_WIDTH   1
#define CRL_APB_BLOCKONLY_RST_DEBUG_ONLY_MASK    0X00000001

/**
 * Register: CRL_APB_RESET_REASON
 */
#define CRL_APB_RESET_REASON    ( ( CRL_APB_BASEADDR ) + 0X00000220 )

#define CRL_APB_RESET_REASON_MIMIC_SHIFT   15
#define CRL_APB_RESET_REASON_MIMIC_WIDTH   1
#define CRL_APB_RESET_REASON_MIMIC_MASK    0X00008000

#define CRL_APB_RESET_REASON_DEBUG_SYS_SHIFT   6
#define CRL_APB_RESET_REASON_DEBUG_SYS_WIDTH   1
#define CRL_APB_RESET_REASON_DEBUG_SYS_MASK    0X00000040

#define CRL_APB_RESET_REASON_SOFT_SHIFT   5
#define CRL_APB_RESET_REASON_SOFT_WIDTH   1
#define CRL_APB_RESET_REASON_SOFT_MASK    0X00000020

#define CRL_APB_RESET_REASON_SRST_SHIFT   4
#define CRL_APB_RESET_REASON_SRST_WIDTH   1
#define CRL_APB_RESET_REASON_SRST_MASK    0X00000010

#define CRL_APB_RESET_REASON_PSONLY_RESET_REQ_SHIFT   3
#define CRL_APB_RESET_REASON_PSONLY_RESET_REQ_WIDTH   1
#define CRL_APB_RESET_REASON_PSONLY_RESET_REQ_MASK    0X00000008

#define CRL_APB_RESET_REASON_PMU_SYS_RESET_SHIFT   2
#define CRL_APB_RESET_REASON_PMU_SYS_RESET_WIDTH   1
#define CRL_APB_RESET_REASON_PMU_SYS_RESET_MASK    0X00000004

#define CRL_APB_RESET_REASON_INTERNAL_POR_SHIFT   1
#define CRL_APB_RESET_REASON_INTERNAL_POR_WIDTH   1
#define CRL_APB_RESET_REASON_INTERNAL_POR_MASK    0X00000002

#define CRL_APB_RESET_REASON_EXTERNAL_POR_SHIFT   0
#define CRL_APB_RESET_REASON_EXTERNAL_POR_WIDTH   1
#define CRL_APB_RESET_REASON_EXTERNAL_POR_MASK    0X00000001

/**
 * Register: CRL_APB_RST_LPD_IOU0
 */
#define CRL_APB_RST_LPD_IOU0    ( ( CRL_APB_BASEADDR ) + 0X00000230 )

#define CRL_APB_RST_LPD_IOU0_GEM3_RESET_SHIFT   3
#define CRL_APB_RST_LPD_IOU0_GEM3_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU0_GEM3_RESET_MASK    0X00000008

#define CRL_APB_RST_LPD_IOU0_GEM2_RESET_SHIFT   2
#define CRL_APB_RST_LPD_IOU0_GEM2_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU0_GEM2_RESET_MASK    0X00000004

#define CRL_APB_RST_LPD_IOU0_GEM1_RESET_SHIFT   1
#define CRL_APB_RST_LPD_IOU0_GEM1_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU0_GEM1_RESET_MASK    0X00000002

#define CRL_APB_RST_LPD_IOU0_GEM0_RESET_SHIFT   0
#define CRL_APB_RST_LPD_IOU0_GEM0_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU0_GEM0_RESET_MASK    0X00000001

/**
 * Register: CRL_APB_RST_LPD_IOU1
 */
#define CRL_APB_RST_LPD_IOU1    ( ( CRL_APB_BASEADDR ) + 0X00000234 )

/**
 * Register: CRL_APB_RST_LPD_IOU2
 */
#define CRL_APB_RST_LPD_IOU2    ( ( CRL_APB_BASEADDR ) + 0X00000238 )

#define CRL_APB_RST_LPD_IOU2_TIMESTAMP_RESET_SHIFT   20
#define CRL_APB_RST_LPD_IOU2_TIMESTAMP_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_TIMESTAMP_RESET_MASK    0X00100000

#define CRL_APB_RST_LPD_IOU2_IOU_CC_RESET_SHIFT   19
#define CRL_APB_RST_LPD_IOU2_IOU_CC_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_IOU_CC_RESET_MASK    0X00080000

#define CRL_APB_RST_LPD_IOU2_GPIO_RESET_SHIFT   18
#define CRL_APB_RST_LPD_IOU2_GPIO_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_GPIO_RESET_MASK    0X00040000

#define CRL_APB_RST_LPD_IOU2_ADMA_RESET_SHIFT   17
#define CRL_APB_RST_LPD_IOU2_ADMA_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_ADMA_RESET_MASK    0X00020000

#define CRL_APB_RST_LPD_IOU2_NAND_RESET_SHIFT   16
#define CRL_APB_RST_LPD_IOU2_NAND_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_NAND_RESET_MASK    0X00010000

#define CRL_APB_RST_LPD_IOU2_SWDT_RESET_SHIFT   15
#define CRL_APB_RST_LPD_IOU2_SWDT_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_SWDT_RESET_MASK    0X00008000

#define CRL_APB_RST_LPD_IOU2_TTC3_RESET_SHIFT   14
#define CRL_APB_RST_LPD_IOU2_TTC3_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_TTC3_RESET_MASK    0X00004000

#define CRL_APB_RST_LPD_IOU2_TTC2_RESET_SHIFT   13
#define CRL_APB_RST_LPD_IOU2_TTC2_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_TTC2_RESET_MASK    0X00002000

#define CRL_APB_RST_LPD_IOU2_TTC1_RESET_SHIFT   12
#define CRL_APB_RST_LPD_IOU2_TTC1_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_TTC1_RESET_MASK    0X00001000

#define CRL_APB_RST_LPD_IOU2_TTC0_RESET_SHIFT   11
#define CRL_APB_RST_LPD_IOU2_TTC0_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_TTC0_RESET_MASK    0X00000800

#define CRL_APB_RST_LPD_IOU2_I2C1_RESET_SHIFT   10
#define CRL_APB_RST_LPD_IOU2_I2C1_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_I2C1_RESET_MASK    0X00000400

#define CRL_APB_RST_LPD_IOU2_I2C0_RESET_SHIFT   9
#define CRL_APB_RST_LPD_IOU2_I2C0_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_I2C0_RESET_MASK    0X00000200

#define CRL_APB_RST_LPD_IOU2_CAN1_RESET_SHIFT   8
#define CRL_APB_RST_LPD_IOU2_CAN1_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_CAN1_RESET_MASK    0X00000100

#define CRL_APB_RST_LPD_IOU2_CAN0_RESET_SHIFT   7
#define CRL_APB_RST_LPD_IOU2_CAN0_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_CAN0_RESET_MASK    0X00000080

#define CRL_APB_RST_LPD_IOU2_SDIO1_RESET_SHIFT   6
#define CRL_APB_RST_LPD_IOU2_SDIO1_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_SDIO1_RESET_MASK    0X00000040

#define CRL_APB_RST_LPD_IOU2_SDIO0_RESET_SHIFT   5
#define CRL_APB_RST_LPD_IOU2_SDIO0_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_SDIO0_RESET_MASK    0X00000020

#define CRL_APB_RST_LPD_IOU2_SPI1_RESET_SHIFT   4
#define CRL_APB_RST_LPD_IOU2_SPI1_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_SPI1_RESET_MASK    0X00000010

#define CRL_APB_RST_LPD_IOU2_SPI0_RESET_SHIFT   3
#define CRL_APB_RST_LPD_IOU2_SPI0_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_SPI0_RESET_MASK    0X00000008

#define CRL_APB_RST_LPD_IOU2_UART1_RESET_SHIFT   2
#define CRL_APB_RST_LPD_IOU2_UART1_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_UART1_RESET_MASK    0X00000004

#define CRL_APB_RST_LPD_IOU2_UART0_RESET_SHIFT   1
#define CRL_APB_RST_LPD_IOU2_UART0_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_UART0_RESET_MASK    0X00000002

#define CRL_APB_RST_LPD_IOU2_QSPI_RESET_SHIFT   0
#define CRL_APB_RST_LPD_IOU2_QSPI_RESET_WIDTH   1
#define CRL_APB_RST_LPD_IOU2_QSPI_RESET_MASK    0X00000001

/**
 * Register: CRL_APB_RST_LPD_TOP
 */
#define CRL_APB_RST_LPD_TOP    ( ( CRL_APB_BASEADDR ) + 0X0000023C )

#define CRL_APB_RST_LPD_TOP_FPD_RESET_SHIFT   23
#define CRL_APB_RST_LPD_TOP_FPD_RESET_WIDTH   1
#define CRL_APB_RST_LPD_TOP_FPD_RESET_MASK    0X00800000

#define CRL_APB_RST_LPD_TOP_AFI_FM6_RESET_SHIFT   19
#define CRL_APB_RST_LPD_TOP_AFI_FM6_RESET_WIDTH   1
#define CRL_APB_RST_LPD_TOP_AFI_FM6_RESET_MASK    0X00080000

#define CRL_APB_RST_LPD_TOP_SYSMON_RESET_SHIFT   17
#define CRL_APB_RST_LPD_TOP_SYSMON_RESET_WIDTH   1
#define CRL_APB_RST_LPD_TOP_SYSMON_RESET_MASK    0X00020000

#define CRL_APB_RST_LPD_TOP_RTC_RESET_SHIFT   16
#define CRL_APB_RST_LPD_TOP_RTC_RESET_WIDTH   1
#define CRL_APB_RST_LPD_TOP_RTC_RESET_MASK    0X00010000

#define CRL_APB_RST_LPD_TOP_APM_RESET_SHIFT   15
#define CRL_APB_RST_LPD_TOP_APM_RESET_WIDTH   1
#define CRL_APB_RST_LPD_TOP_APM_RESET_MASK    0X00008000

#define CRL_APB_RST_LPD_TOP_IPI_RESET_SHIFT   14
#define CRL_APB_RST_LPD_TOP_IPI_RESET_WIDTH   1
#define CRL_APB_RST_LPD_TOP_IPI_RESET_MASK    0X00004000

#define CRL_APB_RST_LPD_TOP_USB1_APB_RESET_SHIFT   11
#define CRL_APB_RST_LPD_TOP_USB1_APB_RESET_WIDTH   1
#define CRL_APB_RST_LPD_TOP_USB1_APB_RESET_MASK    0X00000800

#define CRL_APB_RST_LPD_TOP_USB0_APB_RESET_SHIFT   10
#define CRL_APB_RST_LPD_TOP_USB0_APB_RESET_WIDTH   1
#define CRL_APB_RST_LPD_TOP_USB0_APB_RESET_MASK    0X00000400

#define CRL_APB_RST_LPD_TOP_USB1_HIBERRESET_SHIFT   9
#define CRL_APB_RST_LPD_TOP_USB1_HIBERRESET_WIDTH   1
#define CRL_APB_RST_LPD_TOP_USB1_HIBERRESET_MASK    0X00000200

#define CRL_APB_RST_LPD_TOP_USB0_HIBERRESET_SHIFT   8
#define CRL_APB_RST_LPD_TOP_USB0_HIBERRESET_WIDTH   1
#define CRL_APB_RST_LPD_TOP_USB0_HIBERRESET_MASK    0X00000100

#define CRL_APB_RST_LPD_TOP_USB1_CORERESET_SHIFT   7
#define CRL_APB_RST_LPD_TOP_USB1_CORERESET_WIDTH   1
#define CRL_APB_RST_LPD_TOP_USB1_CORERESET_MASK    0X00000080

#define CRL_APB_RST_LPD_TOP_USB0_CORERESET_SHIFT   6
#define CRL_APB_RST_LPD_TOP_USB0_CORERESET_WIDTH   1
#define CRL_APB_RST_LPD_TOP_USB0_CORERESET_MASK    0X00000040

#define CRL_APB_RST_LPD_TOP_RPU_PGE_RESET_SHIFT   4
#define CRL_APB_RST_LPD_TOP_RPU_PGE_RESET_WIDTH   1
#define CRL_APB_RST_LPD_TOP_RPU_PGE_RESET_MASK    0X00000010

#define CRL_APB_RST_LPD_TOP_OCM_RESET_SHIFT   3
#define CRL_APB_RST_LPD_TOP_OCM_RESET_WIDTH   1
#define CRL_APB_RST_LPD_TOP_OCM_RESET_MASK    0X00000008

#define CRL_APB_RST_LPD_TOP_RPU_AMBA_RESET_SHIFT   2
#define CRL_APB_RST_LPD_TOP_RPU_AMBA_RESET_WIDTH   1
#define CRL_APB_RST_LPD_TOP_RPU_AMBA_RESET_MASK    0X00000004

#define CRL_APB_RST_LPD_TOP_RPU_R51_RESET_SHIFT   1
#define CRL_APB_RST_LPD_TOP_RPU_R51_RESET_WIDTH   1
#define CRL_APB_RST_LPD_TOP_RPU_R51_RESET_MASK    0X00000002

#define CRL_APB_RST_LPD_TOP_RPU_R50_RESET_SHIFT   0
#define CRL_APB_RST_LPD_TOP_RPU_R50_RESET_WIDTH   1
#define CRL_APB_RST_LPD_TOP_RPU_R50_RESET_MASK    0X00000001

/**
 * Register: CRL_APB_RST_LPD_DBG
 */
#define CRL_APB_RST_LPD_DBG    ( ( CRL_APB_BASEADDR ) + 0X00000240 )

#define CRL_APB_RST_LPD_DBG_RPU_DBG1_RESET_SHIFT   5
#define CRL_APB_RST_LPD_DBG_RPU_DBG1_RESET_WIDTH   1
#define CRL_APB_RST_LPD_DBG_RPU_DBG1_RESET_MASK    0X00000020

#define CRL_APB_RST_LPD_DBG_RPU_DBG0_RESET_SHIFT   4
#define CRL_APB_RST_LPD_DBG_RPU_DBG0_RESET_WIDTH   1
#define CRL_APB_RST_LPD_DBG_RPU_DBG0_RESET_MASK    0X00000010

#define CRL_APB_RST_LPD_DBG_DBG_LPD_RESET_SHIFT   1
#define CRL_APB_RST_LPD_DBG_DBG_LPD_RESET_WIDTH   1
#define CRL_APB_RST_LPD_DBG_DBG_LPD_RESET_MASK    0X00000002

#define CRL_APB_RST_LPD_DBG_DBG_FPD_RESET_SHIFT   0
#define CRL_APB_RST_LPD_DBG_DBG_FPD_RESET_WIDTH   1
#define CRL_APB_RST_LPD_DBG_DBG_FPD_RESET_MASK    0X00000001

/**
 * Register: CRL_APB_BOOT_PIN_CTRL
 */
#define CRL_APB_BOOT_PIN_CTRL    ( ( CRL_APB_BASEADDR ) + 0X00000250 )

#define CRL_APB_BOOT_PIN_CTRL_OUT_VAL_SHIFT   8
#define CRL_APB_BOOT_PIN_CTRL_OUT_VAL_WIDTH   4
#define CRL_APB_BOOT_PIN_CTRL_OUT_VAL_MASK    0X00000F00

#define CRL_APB_BOOT_PIN_CTRL_IN_VAL_SHIFT   4
#define CRL_APB_BOOT_PIN_CTRL_IN_VAL_WIDTH   4
#define CRL_APB_BOOT_PIN_CTRL_IN_VAL_MASK    0X000000F0

#define CRL_APB_BOOT_PIN_CTRL_OUT_EN_SHIFT   0
#define CRL_APB_BOOT_PIN_CTRL_OUT_EN_WIDTH   4
#define CRL_APB_BOOT_PIN_CTRL_OUT_EN_MASK    0X0000000F

/**
 * Register: CRL_APB_DED_IOB_CTRL0
 */
#define CRL_APB_DED_IOB_CTRL0    ( ( CRL_APB_BASEADDR ) + 0X00000254 )

#define CRL_APB_DED_IOB_CTRL0_DRIVE0_SHIFT   0
#define CRL_APB_DED_IOB_CTRL0_DRIVE0_WIDTH   4
#define CRL_APB_DED_IOB_CTRL0_DRIVE0_MASK    0X0000000F

/**
 * Register: CRL_APB_DED_IOB_CTRL1
 */
#define CRL_APB_DED_IOB_CTRL1    ( ( CRL_APB_BASEADDR ) + 0X00000258 )

#define CRL_APB_DED_IOB_CTRL1_DRIVE1_SHIFT   0
#define CRL_APB_DED_IOB_CTRL1_DRIVE1_WIDTH   4
#define CRL_APB_DED_IOB_CTRL1_DRIVE1_MASK    0X0000000F

/**
 * Register: CRL_APB_DED_IOB_CTRL2
 */
#define CRL_APB_DED_IOB_CTRL2    ( ( CRL_APB_BASEADDR ) + 0X0000025C )

#define CRL_APB_DED_IOB_CTRL2_DRIVE2_SHIFT   0
#define CRL_APB_DED_IOB_CTRL2_DRIVE2_WIDTH   4
#define CRL_APB_DED_IOB_CTRL2_DRIVE2_MASK    0X0000000F

/**
 * Register: CRL_APB_DED_IOB_CTRL3
 */
#define CRL_APB_DED_IOB_CTRL3    ( ( CRL_APB_BASEADDR ) + 0X00000260 )

#define CRL_APB_DED_IOB_CTRL3_SCHMITT_CMOS_N_SHIFT   0
#define CRL_APB_DED_IOB_CTRL3_SCHMITT_CMOS_N_WIDTH   4
#define CRL_APB_DED_IOB_CTRL3_SCHMITT_CMOS_N_MASK    0X0000000F

/**
 * Register: CRL_APB_DED_IOB_CTRL4
 */
#define CRL_APB_DED_IOB_CTRL4    ( ( CRL_APB_BASEADDR ) + 0X00000264 )

#define CRL_APB_DED_IOB_CTRL4_PULL_HIGH_LOW_N_SHIFT   0
#define CRL_APB_DED_IOB_CTRL4_PULL_HIGH_LOW_N_WIDTH   4
#define CRL_APB_DED_IOB_CTRL4_PULL_HIGH_LOW_N_MASK    0X0000000F

/**
 * Register: CRL_APB_DED_IOB_CTRL5
 */
#define CRL_APB_DED_IOB_CTRL5    ( ( CRL_APB_BASEADDR ) + 0X00000268 )

#define CRL_APB_DED_IOB_CTRL5_PULL_ENABLE_SHIFT   0
#define CRL_APB_DED_IOB_CTRL5_PULL_ENABLE_WIDTH   4
#define CRL_APB_DED_IOB_CTRL5_PULL_ENABLE_MASK    0X0000000F

/**
 * Register: CRL_APB_DED_IOB_CTRL6
 */
#define CRL_APB_DED_IOB_CTRL6    ( ( CRL_APB_BASEADDR ) + 0X0000026C )

#define CRL_APB_DED_IOB_CTRL6_SLOW_FAST_SLEW_N_SHIFT   0
#define CRL_APB_DED_IOB_CTRL6_SLOW_FAST_SLEW_N_WIDTH   4
#define CRL_APB_DED_IOB_CTRL6_SLOW_FAST_SLEW_N_MASK    0X0000000F

#ifdef __cplusplus
}
#endif


#endif /* _CRL_APB_H_ */

