#include <stdbool.h>
#include <stdint.h>
#include <assert.h>

#include "aarch64-smc-asm.h"

enum pm_api_id {
        PM_GET_API_VERSION = 1,
        PM_SYSTEM_SHUTDOWN = 12,
        PM_REQUEST_NODE = 13,
        PM_RELEASE_NODE,
        PM_SET_REQUIREMENT,
        PM_RESET_ASSERT = 17,
        PM_RESET_GET_STATUS,
        PM_PM_INIT_FINALIZE = 21,
        PM_FPGA_LOAD,
        PM_FPGA_GET_STATUS,
        PM_GET_CHIPID = 24,
        PM_IOCTL = 34,
        PM_QUERY_DATA,
        PM_CLOCK_ENABLE,
        PM_CLOCK_DISABLE,
        PM_CLOCK_GETSTATE,
        PM_CLOCK_SETDIVIDER,
        PM_CLOCK_GETDIVIDER,
        PM_CLOCK_SETRATE,
        PM_CLOCK_GETRATE,
        PM_CLOCK_SETPARENT,
        PM_CLOCK_GETPARENT,
        PM_SECURE_AES = 47,
        PM_FEATURE_CHECK = 63,
        PM_API_MAX,
};

enum zynqmp_pm_reset {
        ZYNQMP_PM_RESET_START = 1000,
        ZYNQMP_PM_RESET_PCIE_CFG = ZYNQMP_PM_RESET_START,
        ZYNQMP_PM_RESET_PCIE_BRIDGE,
        ZYNQMP_PM_RESET_PCIE_CTRL,
        ZYNQMP_PM_RESET_DP,
        ZYNQMP_PM_RESET_SWDT_CRF,
        ZYNQMP_PM_RESET_AFI_FM5,
        ZYNQMP_PM_RESET_AFI_FM4,
        ZYNQMP_PM_RESET_AFI_FM3,
        ZYNQMP_PM_RESET_AFI_FM2,
        ZYNQMP_PM_RESET_AFI_FM1,
        ZYNQMP_PM_RESET_AFI_FM0,
        ZYNQMP_PM_RESET_GDMA,
        ZYNQMP_PM_RESET_GPU_PP1,
        ZYNQMP_PM_RESET_GPU_PP0,
        ZYNQMP_PM_RESET_GPU,
        ZYNQMP_PM_RESET_GT,
        ZYNQMP_PM_RESET_SATA,
        ZYNQMP_PM_RESET_ACPU3_PWRON,
        ZYNQMP_PM_RESET_ACPU2_PWRON,
        ZYNQMP_PM_RESET_ACPU1_PWRON,
        ZYNQMP_PM_RESET_ACPU0_PWRON,
        ZYNQMP_PM_RESET_APU_L2,
        ZYNQMP_PM_RESET_ACPU3,
        ZYNQMP_PM_RESET_ACPU2,
        ZYNQMP_PM_RESET_ACPU1,
        ZYNQMP_PM_RESET_ACPU0,
        ZYNQMP_PM_RESET_DDR,
        ZYNQMP_PM_RESET_APM_FPD,
        ZYNQMP_PM_RESET_SOFT,
        ZYNQMP_PM_RESET_GEM0,
        ZYNQMP_PM_RESET_GEM1,
        ZYNQMP_PM_RESET_GEM2,
        ZYNQMP_PM_RESET_GEM3,
        ZYNQMP_PM_RESET_QSPI,
        ZYNQMP_PM_RESET_UART0,
        ZYNQMP_PM_RESET_UART1,
        ZYNQMP_PM_RESET_SPI0,
        ZYNQMP_PM_RESET_SPI1,
        ZYNQMP_PM_RESET_SDIO0,
        ZYNQMP_PM_RESET_SDIO1,
        ZYNQMP_PM_RESET_CAN0,
        ZYNQMP_PM_RESET_CAN1,
        ZYNQMP_PM_RESET_I2C0,
        ZYNQMP_PM_RESET_I2C1,
        ZYNQMP_PM_RESET_TTC0,
        ZYNQMP_PM_RESET_TTC1,
        ZYNQMP_PM_RESET_TTC2,
        ZYNQMP_PM_RESET_TTC3,
        ZYNQMP_PM_RESET_SWDT_CRL,
        ZYNQMP_PM_RESET_NAND,
        ZYNQMP_PM_RESET_ADMA,
        ZYNQMP_PM_RESET_GPIO,
        ZYNQMP_PM_RESET_IOU_CC,
        ZYNQMP_PM_RESET_TIMESTAMP,
        ZYNQMP_PM_RESET_RPU_R50,
        ZYNQMP_PM_RESET_RPU_R51,
        ZYNQMP_PM_RESET_RPU_AMBA,
        ZYNQMP_PM_RESET_OCM,
        ZYNQMP_PM_RESET_RPU_PGE,
        ZYNQMP_PM_RESET_USB0_CORERESET,
        ZYNQMP_PM_RESET_USB1_CORERESET,
        ZYNQMP_PM_RESET_USB0_HIBERRESET,
        ZYNQMP_PM_RESET_USB1_HIBERRESET,
        ZYNQMP_PM_RESET_USB0_APB,
        ZYNQMP_PM_RESET_USB1_APB,
        ZYNQMP_PM_RESET_IPI,
        ZYNQMP_PM_RESET_APM_LPD,
        ZYNQMP_PM_RESET_RTC,
        ZYNQMP_PM_RESET_SYSMON,
        ZYNQMP_PM_RESET_AFI_FM6,
        ZYNQMP_PM_RESET_LPD_SWDT,
        ZYNQMP_PM_RESET_FPD,
        ZYNQMP_PM_RESET_RPU_DBG1,
        ZYNQMP_PM_RESET_RPU_DBG0,
        ZYNQMP_PM_RESET_DBG_LPD,
        ZYNQMP_PM_RESET_DBG_FPD,
        ZYNQMP_PM_RESET_APLL,
        ZYNQMP_PM_RESET_DPLL,
        ZYNQMP_PM_RESET_VPLL,
        ZYNQMP_PM_RESET_IOPLL,
        ZYNQMP_PM_RESET_RPLL,
        ZYNQMP_PM_RESET_GPO3_PL_0,
        ZYNQMP_PM_RESET_GPO3_PL_1,
        ZYNQMP_PM_RESET_GPO3_PL_2,
        ZYNQMP_PM_RESET_GPO3_PL_3,
        ZYNQMP_PM_RESET_GPO3_PL_4,
        ZYNQMP_PM_RESET_GPO3_PL_5,
        ZYNQMP_PM_RESET_GPO3_PL_6,
        ZYNQMP_PM_RESET_GPO3_PL_7,
        ZYNQMP_PM_RESET_GPO3_PL_8,
        ZYNQMP_PM_RESET_GPO3_PL_9,
        ZYNQMP_PM_RESET_GPO3_PL_10,
        ZYNQMP_PM_RESET_GPO3_PL_11,
        ZYNQMP_PM_RESET_GPO3_PL_12,
        ZYNQMP_PM_RESET_GPO3_PL_13,
        ZYNQMP_PM_RESET_GPO3_PL_14,
        ZYNQMP_PM_RESET_GPO3_PL_15,
        ZYNQMP_PM_RESET_GPO3_PL_16,
        ZYNQMP_PM_RESET_GPO3_PL_17,
        ZYNQMP_PM_RESET_GPO3_PL_18,
        ZYNQMP_PM_RESET_GPO3_PL_19,
        ZYNQMP_PM_RESET_GPO3_PL_20,
        ZYNQMP_PM_RESET_GPO3_PL_21,
        ZYNQMP_PM_RESET_GPO3_PL_22,
        ZYNQMP_PM_RESET_GPO3_PL_23,
        ZYNQMP_PM_RESET_GPO3_PL_24,
        ZYNQMP_PM_RESET_GPO3_PL_25,
        ZYNQMP_PM_RESET_GPO3_PL_26,
        ZYNQMP_PM_RESET_GPO3_PL_27,
        ZYNQMP_PM_RESET_GPO3_PL_28,
        ZYNQMP_PM_RESET_GPO3_PL_29,
        ZYNQMP_PM_RESET_GPO3_PL_30,
        ZYNQMP_PM_RESET_GPO3_PL_31,
        ZYNQMP_PM_RESET_RPU_LS,
        ZYNQMP_PM_RESET_PS_ONLY,
        ZYNQMP_PM_RESET_PL,
        ZYNQMP_PM_RESET_PS_PL0,
        ZYNQMP_PM_RESET_PS_PL1,
        ZYNQMP_PM_RESET_PS_PL2,
        ZYNQMP_PM_RESET_PS_PL3,
        ZYNQMP_PM_RESET_END = ZYNQMP_PM_RESET_PS_PL3
};

bool plat_psci_cpu_on(unsigned int cpu, uintptr_t entry);
bool plat_psci_cpu_off(unsigned int cpu);

uint64_t aarch64_smc_decode(struct excp_frame *f);

static inline uintptr_t aarch64_smc(unsigned int callnr,
				    uintptr_t arg1,
				    uintptr_t arg2,
				    uintptr_t arg3,
				    uintptr_t arg4,
				    uintptr_t arg5,
				    uintptr_t sess_id,
				    uint32_t hyp_id)
{
	register uintptr_t a0 asm("x0") = callnr;
	register uintptr_t a1 asm("x1") = arg1;
	register uintptr_t a2 asm("x2") = arg2;
	register uintptr_t a3 asm("x3") = arg3;
	register uintptr_t a4 asm("x4") = arg4;
	register uintptr_t a5 asm("x5") = arg5;
	register uintptr_t a6 asm("x6") = sess_id;
	register uintptr_t a7 asm("x7") = hyp_id;

	asm volatile ("smc\t0\n"
			: "=r" (a0), "=r"(a1), "=r" (a2), "=r" (a3)
			:	"0" (a0),
				"r" (a1),
				"r" (a2),
				"r" (a3),
				"r" (a4),
				"r" (a5),
				"r" (a6),
				"r" (a7));
	return a0;
}
