#!/bin/sh
#
# Copyright 2009 (c) Edgar E. Iglesias <edgar.iglesias@gmail.com>
#
# syms_elf2ldscript.sh
#
# Script to create symtabs suitable for inclusion in linkerscripts from an
# ELF file.
#

NM=nm
ELF_FILE=$1
PREFIX=$2

cat <<EOF
/*
 * DO NOT EDIT.
 *
 * Auto-generated by syms_elf2ldscript.sh.
 *
 *
 * $0 $*
 */

EOF

${NM} -n --special-syms ${ELF_FILE} | awk "{ print \"$PREFIX\" \$3 \" = 0x\" \$1 \";\"}"
